// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AtlantaApi.Feature.BeWiser.QuoteService.SavePaymentInfo.V1
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "BeWiser")]
    public partial class ValidateSavePaymentInfoSingleFieldInCaseCallToCDLUsingTotalAmountFeature : object, Xunit.IClassFixture<ValidateSavePaymentInfoSingleFieldInCaseCallToCDLUsingTotalAmountFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = new string[] {
                "BeWiser"};
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "SavePaymentInfoTotalAmountSentToCDL.feature"
#line hidden
        
        public ValidateSavePaymentInfoSingleFieldInCaseCallToCDLUsingTotalAmountFeature(ValidateSavePaymentInfoSingleFieldInCaseCallToCDLUsingTotalAmountFeature.FixtureData fixtureData, AtlantaApi_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Feature/BeWiser/QuoteService/SavePaymentInfo/V1", "Validate Save Payment Info Single Field In Case Call To CDL using TotalAmount", null, ProgrammingLanguage.CSharp, new string[] {
                        "BeWiser"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Validate Save Payment Info With TotalAmount caculated sent to CDL")]
        [Xunit.TraitAttribute("FeatureTitle", "Validate Save Payment Info Single Field In Case Call To CDL using TotalAmount")]
        [Xunit.TraitAttribute("Description", "Validate Save Payment Info With TotalAmount caculated sent to CDL")]
        [Xunit.TraitAttribute("Category", "QuoteServices")]
        [Xunit.InlineDataAttribute("payinfull", "Yes", "Yes", "200", "true", "Save data successfully", new string[0])]
        [Xunit.InlineDataAttribute("payinfull", "No", "Yes", "200", "true", "Save data successfully", new string[0])]
        [Xunit.InlineDataAttribute("payinfull", "No", "No", "400", "false", "TotalAmountToPay is incorrectly calculated", new string[0])]
        [Xunit.InlineDataAttribute("payinfull", "yes", "No", "400", "false", "TotalAmountToPay is incorrectly calculated", new string[0])]
        [Xunit.InlineDataAttribute("Instalmnts", "Yes", "Yes", "200", "true", "Save data successfully", new string[0])]
        [Xunit.InlineDataAttribute("Instalmnts", "No", "Yes", "200", "true", "Save data successfully", new string[0])]
        [Xunit.InlineDataAttribute("Instalmnts", "No", "No", "400", "false", "TotalAmountToPay is incorrectly calculated", new string[0])]
        [Xunit.InlineDataAttribute("Instalmnts", "yes", "No", "400", "false", "TotalAmountToPay is incorrectly calculated", new string[0])]
        public virtual void ValidateSavePaymentInfoWithTotalAmountCaculatedSentToCDL(string paymnetMethod, string optionalExtras, string totalAmountToPay, string statusCode, string isSuccess, string messages, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "QuoteServices"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("PaymnetMethod", paymnetMethod);
            argumentsOfScenario.Add("OptionalExtras", optionalExtras);
            argumentsOfScenario.Add("TotalAmountToPay", totalAmountToPay);
            argumentsOfScenario.Add("StatusCode", statusCode);
            argumentsOfScenario.Add("IsSuccess", isSuccess);
            argumentsOfScenario.Add("Messages", messages);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Validate Save Payment Info With TotalAmount caculated sent to CDL", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 9
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table159 = new TechTalk.SpecFlow.Table(new string[] {
                            "Property",
                            "Value"});
                table159.AddRow(new string[] {
                            "PrepurchaseRequestBody",
                            "SavePaymentInfoRequestBodyPaymentMethodBeWiser.json"});
                table159.AddRow(new string[] {
                            "QuoteRequestBody",
                            "ValidQuoteBeWiserSuccess.json"});
                table159.AddRow(new string[] {
                            "ApiVersion",
                            "V3"});
                table159.AddRow(new string[] {
                            "ContextName",
                            "BeWiser"});
#line 10
 testRunner.Given("User has prepurchase body", ((string)(null)), table159, "Given ");
#line hidden
#line 17
 testRunner.When(string.Format("User sends save payment info request with PaymentMethod {0} and OptionalExtras {1" +
                            "} and {2}", paymnetMethod, optionalExtras, totalAmountToPay), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 18
 testRunner.Then(string.Format("Prepurchase response returns {0} and {1} and {2}", statusCode, isSuccess, messages), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                ValidateSavePaymentInfoSingleFieldInCaseCallToCDLUsingTotalAmountFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                ValidateSavePaymentInfoSingleFieldInCaseCallToCDLUsingTotalAmountFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
