// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AtlantaApi.Feature.ANVanClassic.ReferenceDataService.V0
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "AutonetVan")]
    public partial class CheckHeaderValidationAndNormalCasesFeature : object, Xunit.IClassFixture<CheckHeaderValidationAndNormalCasesFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = new string[] {
                "AutonetVan"};
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CheckHeaderValidationAndNormalCases.feature"
#line hidden
        
        public CheckHeaderValidationAndNormalCasesFeature(CheckHeaderValidationAndNormalCasesFeature.FixtureData fixtureData, AtlantaApi_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Feature/ANVanClassic/ReferenceDataService/V0", "CheckHeaderValidationAndNormalCases", null, ProgrammingLanguage.CSharp, new string[] {
                        "AutonetVan"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Send reference data request with header")]
        [Xunit.TraitAttribute("FeatureTitle", "CheckHeaderValidationAndNormalCases")]
        [Xunit.TraitAttribute("Description", "Send reference data request with header")]
        [Xunit.TraitAttribute("Category", "ReferenceDataServices")]
        [Xunit.InlineDataAttribute("/api/reference-data/metadata", "ContextNull", "400", "Tenant is not supported", new string[0])]
        [Xunit.InlineDataAttribute("/api/reference-data/metadata", "ContextInvalid", "400", "Tenant is not supported", new string[0])]
        [Xunit.InlineDataAttribute("/api/reference-data/metadata-bykeyword", "ContextNull", "400", "Tenant is not supported", new string[0])]
        [Xunit.InlineDataAttribute("/api/reference-data/metadata-bykeyword", "ContextInvalid", "400", "Tenant is not supported", new string[0])]
        [Xunit.InlineDataAttribute("/api/reference-data/metadata-by-value", "ContextNull", "400", "Tenant is not supported", new string[0])]
        [Xunit.InlineDataAttribute("/api/reference-data/metadata-by-value", "ContextInvalid", "400", "Tenant is not supported", new string[0])]
        public virtual void SendReferenceDataRequestWithHeader(string endpoint, string contextName, string statusCode, string message, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "ReferenceDataServices"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Endpoint", endpoint);
            argumentsOfScenario.Add("ContextName", contextName);
            argumentsOfScenario.Add("StatusCode", statusCode);
            argumentsOfScenario.Add("Message", message);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Send reference data request with header", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 9
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table99 = new TechTalk.SpecFlow.Table(new string[] {
                            "Property",
                            "Value"});
                table99.AddRow(new string[] {
                            "ReferenceDataRequestBody",
                            "MetadataBodyAutonetVan.json"});
                table99.AddRow(new string[] {
                            "ApiVersion",
                            "V0"});
                table99.AddRow(new string[] {
                            "ContextName",
                            "AutonetVan"});
#line 10
testRunner.Given("User has Reference Data body", ((string)(null)), table99, "Given ");
#line hidden
#line 15
 testRunner.When(string.Format("User send invalid metadata request with {0} and {1}", endpoint, contextName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 16
 testRunner.Then(string.Format("The Reference Data response should be shown {0} and {1}", statusCode, message), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                CheckHeaderValidationAndNormalCasesFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                CheckHeaderValidationAndNormalCasesFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
