// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AtlantaApi.Feature.SafeGuard.WebHookService.V1
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "SafeGuardMH")]
    public partial class PaymentOutcomeValidationFeature : object, Xunit.IClassFixture<PaymentOutcomeValidationFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = new string[] {
                "SafeGuardMH"};
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "PaymentOutcomeValidation.feature"
#line hidden
        
        public PaymentOutcomeValidationFeature(PaymentOutcomeValidationFeature.FixtureData fixtureData, AtlantaApi_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Feature/SafeGuard/WebHookService/V1", "PaymentOutcomeValidation", null, ProgrammingLanguage.CSharp, new string[] {
                        "SafeGuardMH"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="PaymentOutcomeValidation")]
        [Xunit.TraitAttribute("FeatureTitle", "PaymentOutcomeValidation")]
        [Xunit.TraitAttribute("Description", "PaymentOutcomeValidation")]
        [Xunit.TraitAttribute("Category", "WebhookServices")]
        [Xunit.InlineDataAttribute("MerchantID", "123", "200", "/mh/newbus/confirmation?", new string[0])]
        [Xunit.InlineDataAttribute("NavigationStatus", "COMPLETED", "200", "/mh/newbus/confirmation?", new string[0])]
        [Xunit.InlineDataAttribute("PaymentType", "\"\"", "200", "/mh/newbus/confirmation?", new string[0])]
        [Xunit.InlineDataAttribute("CardTypeValue", "missing", "200", "/mh/newbus/confirmation?", new string[0])]
        [Xunit.InlineDataAttribute("CardTypeValue", "Mastercard", "200", "/mh/newbus/confirmation?", new string[0])]
        [Xunit.InlineDataAttribute("CardHolderName", "Test", "200", "/mh/newbus/confirmation?", new string[0])]
        [Xunit.InlineDataAttribute("ExpiryMonth", "1", "200", "/mh/newbus/confirmation?", new string[0])]
        [Xunit.InlineDataAttribute("IIN", "missing", "200", "/mh/newbus/confirmation?", new string[0])]
        [Xunit.InlineDataAttribute("IIN", "545454", "200", "/mh/newbus/confirmation?", new string[0])]
        [Xunit.InlineDataAttribute("IssueNumber", "556", "200", "/mh/newbus/confirmation?", new string[0])]
        [Xunit.InlineDataAttribute("MaskedCardNumber", "1234", "200", "/mh/newbus/confirmation?", new string[0])]
        [Xunit.InlineDataAttribute("StartMonth", "2", "200", "/mh/newbus/confirmation?", new string[0])]
        [Xunit.InlineDataAttribute("StartYear", "2019", "200", "/mh/newbus/confirmation?", new string[0])]
        public virtual void PaymentOutcomeValidation(string level1, string value, string statusCode, string messages, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "WebhookServices"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Level1", level1);
            argumentsOfScenario.Add("Value", value);
            argumentsOfScenario.Add("StatusCode", statusCode);
            argumentsOfScenario.Add("Messages", messages);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PaymentOutcomeValidation", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 4
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table435 = new TechTalk.SpecFlow.Table(new string[] {
                            "Property",
                            "Value"});
                table435.AddRow(new string[] {
                            "Uri",
                            "/api/V1/payment/outcome/at-sw-sc-mh-SWIN"});
                table435.AddRow(new string[] {
                            "WebHookBody",
                            "WebHookBodyScenicSG.json"});
                table435.AddRow(new string[] {
                            "QuoteRequestBody",
                            "ValidQuoteForSGGetQuote1.json"});
                table435.AddRow(new string[] {
                            "PaymentRequestBody",
                            "RegisterPaymentRequestBodyScenicMH.json"});
                table435.AddRow(new string[] {
                            "SaveMarketingRequestBody",
                            "SaveMarketingRequestBodyScenicMH.json"});
                table435.AddRow(new string[] {
                            "SavePaymentInfoRequestBody",
                            "SavePaymentInfoSGquestBodyPayInFull.json"});
                table435.AddRow(new string[] {
                            "SaveCardConsentBody",
                            "SaveCardConsentBodyForSG.json"});
                table435.AddRow(new string[] {
                            "ApiVersion0",
                            "V0"});
                table435.AddRow(new string[] {
                            "ApiVersion1",
                            "V1"});
                table435.AddRow(new string[] {
                            "ApiVersion2",
                            "V2"});
                table435.AddRow(new string[] {
                            "ContextName",
                            "SafeGuardMH"});
#line 5
 testRunner.Given("I have wrapUp table for SG", ((string)(null)), table435, "Given ");
#line hidden
#line 19
 testRunner.When("User send a SG Resister Payment service", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table436 = new TechTalk.SpecFlow.Table(new string[] {
                            "Level1",
                            "Value"});
                table436.AddRow(new string[] {
                            string.Format("{0}", level1),
                            string.Format("{0}", value)});
#line 20
 testRunner.And("User send a SG WebHook service with", ((string)(null)), table436, "And ");
#line hidden
#line 23
 testRunner.Then(string.Format("SG Payment response returns {0} and {1}", statusCode, messages), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                PaymentOutcomeValidationFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                PaymentOutcomeValidationFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
