// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AtlantaApi.Feature.ANVanClassic.QuoteService.Quotes.V3
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "AutonetVan")]
    public partial class GetQuoteInvalidRequestCasesFeature : object, Xunit.IClassFixture<GetQuoteInvalidRequestCasesFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = new string[] {
                "AutonetVan"};
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "GetQuoteInvalidRequest.feature"
#line hidden
        
        public GetQuoteInvalidRequestCasesFeature(GetQuoteInvalidRequestCasesFeature.FixtureData fixtureData, AtlantaApi_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Feature/ANVanClassic/QuoteService/Quotes/V3", "Get Quote invalid request cases", null, ProgrammingLanguage.CSharp, new string[] {
                        "AutonetVan"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Get Quote with invalid request param")]
        [Xunit.TraitAttribute("FeatureTitle", "Get Quote invalid request cases")]
        [Xunit.TraitAttribute("Description", "Get Quote with invalid request param")]
        [Xunit.TraitAttribute("Category", "QuoteServices")]
        [Xunit.InlineDataAttribute("/api/v3/quote/quotes", "GET", "False", "404", "NotFound", new string[0])]
        [Xunit.InlineDataAttribute("/api/v3/quote/quotes1", "POST", "False", "404", "NotFound", new string[0])]
        public virtual void GetQuoteWithInvalidRequestParam(string endpoint, string method, string isSuccess, string statusCode, string message, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "QuoteServices"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Endpoint", endpoint);
            argumentsOfScenario.Add("Method", method);
            argumentsOfScenario.Add("IsSuccess", isSuccess);
            argumentsOfScenario.Add("StatusCode", statusCode);
            argumentsOfScenario.Add("Message", message);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get Quote with invalid request param", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 10
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table73 = new TechTalk.SpecFlow.Table(new string[] {
                            "Name",
                            "Value1"});
                table73.AddRow(new string[] {
                            "Url",
                            "QuoteApi"});
                table73.AddRow(new string[] {
                            "ApiVersion",
                            "V3"});
                table73.AddRow(new string[] {
                            "Context",
                            "ContextInvalid"});
                table73.AddRow(new string[] {
                            "JsonBodyFile",
                            "ValidQuoteAutonetVanSuccess.json"});
#line 11
 testRunner.Given("The customer has", ((string)(null)), table73, "Given ");
#line hidden
#line 17
 testRunner.When(string.Format("The customer call quote API validate {0} and {1}", endpoint, method), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 18
 testRunner.Then(string.Format("The message should be shown {0},{1},\"{2}\"", statusCode, isSuccess, message), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                GetQuoteInvalidRequestCasesFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                GetQuoteInvalidRequestCasesFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
