#Cover 471 cases
@CNSBike
Feature: PartialQuoteSingleFieldDataValidationHappyCases

@QuoteServices
Scenario Outline: ValiDate Partial quote API on each field
	Given The customer has 
	| Name         | Value1              |
	| Url          | PartialQuote        |
	| ApiVersion   | V2                  |
	| Context      | CNSelectBikeContext |
	| JsonBodyFile | ValidQuoteCNSBike.json     |
	When The customer call quote API
		| Level1   | Level2   | Level3   | Level4   | Level5   | Level6   | Level7   | Value   |
		| <Level1> | <Level2> | <Level3> | <Level4> | <Level5> | <Level6> | <Level7> | <Value> |
	Then The message should be shown <StatusCode>,<IsSuccess>,"<Message>"
	Examples:	
	| Level1 | Level2                | Level3                      | Level4            | Level5                  | Level6             | Level7 | Value                                                                                                                                 | StatusCode | IsSuccess | Message                          |
	| Risk   | Proposer              | Salutation                  |                   |                         |                    |        | null                                                                                                                                  | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Proposer              | Salutation                  |                   |                         |                    |        | ""                                                                                                                                    | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Proposer              | Salutation                  |                   |                         |                    |        | missing                                                                                                                               | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Proposer              | Salutation                  |                   |                         |                    |        | Mrs Selena abcdfgtrgfdabcdfgtrgfdabcdfgtrgfdabcdfgtrgfdabcdfgtrgfdabcdfgtrgfdabcdfgtrgfdabcdfgtrgfdabcdfgtrgfdabcdfgtrgfdabcdfgtrgfdr | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Proposer              | OtherVehicleUse             |                   |                         |                    |        | missing                                                                                                                               | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Proposer              | OtherVehicleUse             |                   |                         |                    |        | null                                                                                                                                  | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Proposer              | OtherVehicleUse             |                   |                         |                    |        | ""                                                                                                                                    | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Proposer              | Address                     | AbodeType         |                         |                    |        | missing                                                                                                                               | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Proposer              | Address                     | AbodeType         |                         |                    |        | null                                                                                                                                  | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Proposer              | Address                     | AbodeType         |                         |                    |        | ""                                                                                                                                    | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Proposer              | Suffix                      |                   |                         |                    |        | Mrs Selenaz                                                                                                                           | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | AdditionalDrivers | Salutation              |                    |        | null                                                                                                                                  | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | AdditionalDrivers | Salutation              |                    |        | ""                                                                                                                                    | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | AdditionalDrivers | Salutation              |                    |        | missing                                                                                                                               | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | AdditionalDrivers | Suffix                  |                    |        | Mrs Selenaz                                                                                                                           | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | AdditionalDrivers | DrivingLicence          | HoldCbtCertificate |        | null                                                                                                                                  | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | AdditionalDrivers | OtherVehicleUse         |                    |        | missing                                                                                                                               | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | AdditionalDrivers | OtherVehicleUse         |                    |        | null                                                                                                                                  | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | AdditionalDrivers | OtherVehicleUse         |                    |        | ""                                                                                                                                    | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | VehicleDetail     | ProductionPeriod        |                    |        | ""                                                                                                                                    | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | VehicleDetail     | ProductionPeriod        |                    |        | null                                                                                                                                  | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | VehicleDetail     | ProductionPeriod        |                    |        | missing                                                                                                                               | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | VehicleDetail     | BodyStyle               |                    |        | ""                                                                                                                                    | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | VehicleDetail     | BodyStyle               |                    |        | null                                                                                                                                  | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | VehicleDetail     | BodyStyle               |                    |        | missing                                                                                                                               | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | VehicleDetail     | Seats                   |                    |        | ""                                                                                                                                    | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | VehicleDetail     | Seats                   |                    |        | null                                                                                                                                  | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | VehicleDetail     | Seats                   |                    |        | missing                                                                                                                               | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | VehicleDetail     | HandednessDrivingType   |                    |        | ""                                                                                                                                    | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | VehicleDetail     | HandednessDrivingType   |                    |        | null                                                                                                                                  | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | VehicleDetail     | HandednessDrivingType   |                    |        | missing                                                                                                                               | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | VehicleDetail     | Abs                     |                    |        | ""                                                                                                                                    | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | VehicleDetail     | Abs                     |                    |        | null                                                                                                                                  | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | VehicleDetail     | Abs                     |                    |        | missing                                                                                                                               | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | VehicleDetail     | Owner                   |                    |        | null                                                                                                                                  | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | VehicleDetail     | Owner                   |                    |        | missing                                                                                                                               | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | VehicleDetail     | Owner                   |                    |        | ""                                                                                                                                    | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | VehicleDetail     | RegisteredKeeper        |                    |        | ""                                                                                                                                    | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | VehicleDetail     | RegisteredKeeper        |                    |        | null                                                                                                                                  | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | VehicleDetail     | RegisteredKeeper        |                    |        | missing                                                                                                                               | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | VehicleDetail     | LocationParkedOvernight |                    |        | ""                                                                                                                                    | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | VehicleDetail     | LocationParkedOvernight |                    |        | null                                                                                                                                  | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | VehicleDetail     | LocationParkedOvernight |                    |        | missing                                                                                                                               | 200        | TRUE      | Store partial quote successfully |
	| Risk   | MaxNumOfQuotes        |                             |                   |                         |                    |        | -1                                                                                                                                    | 200        | TRUE      | Store partial quote successfully |
	| Risk   | MaxNumOfQuotes        |                             |                   |                         |                    |        | 3.14                                                                                                                                  | 200        | TRUE      | Store partial quote successfully |
	| Risk   | MaxNumOfQuotes        |                             |                   |                         |                    |        | abc                                                                                                                                   | 200        | TRUE      | Store partial quote successfully |
	| Risk   | MaxNumOfQuotesToStore |                             |                   |                         |                    |        | -1                                                                                                                                    | 200        | TRUE      | Store partial quote successfully |
	| Risk   | MaxNumOfQuotesToStore |                             |                   |                         |                    |        | 3.14                                                                                                                                  | 200        | TRUE      | Store partial quote successfully |
	| Risk   | MaxNumOfQuotesToStore |                             |                   |                         |                    |        | abc                                                                                                                                   | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Product               | Claims                      | PersonId          |                         |                    |        | 15                                                                                                                                    | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Product               | Convictions                 | PersonId          |                         |                    |        | 15                                                                                                                                    | 200        | TRUE      | Store partial quote successfully |
	| Risk   | OptionalExtras        | Amount                      |                   |                         |                    |        | -1                                                                                                                                    | 200        | TRUE      | Store partial quote successfully |
	| Risk   | OptionalExtras        | CommissionAmount            |                   |                         |                    |        | -1                                                                                                                                    | 200        | TRUE      | Store partial quote successfully |
	| Risk   | LoyaltyCard           |                             |                   |                         |                    |        | null                                                                                                                                  | 200        | true      | Store partial quote successfully |
	| Risk   | LoyaltyCard           | CardNumber                  |                   |                         |                    |        | null                                                                                                                                  | 200        | true      | Store partial quote successfully |
	| Risk   | LoyaltyCard           | BackMatchPermission         |                   |                         |                    |        | null                                                                                                                                  | 200        | true      | Store partial quote successfully |
	| Risk   | LoyaltyCard           | BackMatchPermission         |                   |                         |                    |        | ""                                                                                                                                    | 200        | true      | Store partial quote successfully |
	| Risk   | LoyaltyCard           | BackMatchPermission         |                   |                         |                    |        | missing                                                                                                                               | 200        | true      | Store partial quote successfully |
	| Risk   | LoyaltyCard           | BackMatchSuccessLevel       |                   |                         |                    |        | null                                                                                                                                  | 200        | true      | Store partial quote successfully |
	| Risk   | LoyaltyCard           | BackMatchSuccessLevel       |                   |                         |                    |        | ""                                                                                                                                    | 200        | TRUE      | Store partial quote successfully |
	| Risk   | LoyaltyCard           | BackMatchSuccessLevel       |                   |                         |                    |        | missing                                                                                                                               | 200        | true      | Store partial quote successfully |
	| Risk   | Proposer              | DrivingLicenceNumber        |                   |                         |                    |        | null                                                                                                                                  | 200        | true      | Store partial quote successfully |
	| Risk   | Proposer              | AdditionalDrivingExperience | Type              |                         |                    |        | AdvanceRider                                                                                                                          | 200        | true      | Store partial quote successfully |
	| Risk   | Proposer              | AdditionalDrivingExperience | Type              |                         |                    |        | 0                                                                                                                                     | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Proposer              | AdditionalDrivingExperience | Type              |                         |                    |        | 1                                                                                                                                     | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Proposer              | AdditionalDrivingExperience | Type              |                         |                    |        | 2                                                                                                                                     | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Proposer              | AdditionalDrivingExperience | Type              |                         |                    |        | 3                                                                                                                                     | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Proposer              | AdditionalDrivingExperience | Type              |                         |                    |        | 4                                                                                                                                     | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Proposer              | AdditionalDrivingExperience | Type              |                         |                    |        | StarRider                                                                                                                             | 200        | true      | Store partial quote successfully |
	| Risk   | Proposer              | AdditionalDrivingExperience | Type              |                         |                    |        | null                                                                                                                                  | 200        | true      | Store partial quote successfully |
	| Risk   | Proposer              | AdditionalDrivingExperience | Code              |                         |                    |        | 0                                                                                                                                     | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Proposer              | AdditionalDrivingExperience | Code              |                         |                    |        | 1                                                                                                                                     | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Proposer              | AdditionalDrivingExperience | Code              |                         |                    |        | 2                                                                                                                                     | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Proposer              | AdditionalDrivingExperience | Code              |                         |                    |        | null                                                                                                                                  | 200        | true      | Store partial quote successfully |
	| Risk   | Proposer              | AdditionalDrivingExperience | Date              |                         |                    |        | null                                                                                                                                  | 200        | true      | Store partial quote successfully |
	| Risk   | Proposer              | AdditionalDrivingExperience | Date              |                         |                    |        | ""                                                                                                                                    | 200        | true      | Store partial quote successfully |
	| Risk   | Proposer              | AdditionalDrivingExperience | Date              |                         |                    |        | missing                                                                                                                               | 200        | true      | Store partial quote successfully |
	| Risk   | Proposer              | AdditionalDrivingExperience | YearsClaimFree    |                         |                    |        | null                                                                                                                                  | 200        | true      | Store partial quote successfully |
	| Risk   | Proposer              | AdditionalDrivingExperience | YearsClaimFree    |                         |                    |        | missing                                                                                                                               | 200        | true      | Store partial quote successfully |
	| Risk   | Proposer              | AdditionalDrivingExperience | YearsClaimFree    |                         |                    |        | 0                                                                                                                                     | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Proposer              | AdditionalDrivingExperience | YearsClaimFree    |                         |                    |        | 9                                                                                                                                     | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Proposer              | PreviousInsurance           | SchemeCode        |                         |                    |        | null                                                                                                                                  | 200        | true      | Store partial quote successfully |
	| Risk   | Proposer              | PreviousInsurance           | SchemeCode        |                         |                    |        | missing                                                                                                                               | 200        | true      | Store partial quote successfully |
	| Risk   | Proposer              | PreviousInsurance           | SchemeCode        |                         |                    |        | XF                                                                                                                                    | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Proposer              | NonRTAConviction            |                   |                         |                    |        | FALSE                                                                                                                                 | 200        | true      | Store partial quote successfully |
	| Risk   | Proposer              | NonRTAConviction            |                   |                         |                    |        | null                                                                                                                                  | 200        | true      | Store partial quote successfully |
	| Risk   | Proposer              | NonRTAConviction            |                   |                         |                    |        | ""                                                                                                                                    | 200        | true      | Store partial quote successfully |
	| Risk   | Proposer              | NonRTAConviction            |                   |                         |                    |        | missing                                                                                                                               | 200        | true      | Store partial quote successfully |
	| Risk   | Proposer              | BankRuptOrCcJ               |                   |                         |                    |        | TRUE                                                                                                                                  | 200        | true      | Store partial quote successfully |
	| Risk   | Proposer              | BankRuptOrCcJ               |                   |                         |                    |        | FALSE                                                                                                                                 | 200        | true      | Store partial quote successfully |
	| Risk   | Proposer              | BankRuptOrCcJ               |                   |                         |                    |        | null                                                                                                                                  | 200        | true      | Store partial quote successfully |
	| Risk   | Proposer              | BankRuptOrCcJ               |                   |                         |                    |        | ""                                                                                                                                    | 200        | true      | Store partial quote successfully |
	| Risk   | Proposer              | BankRuptOrCcJ               |                   |                         |                    |        | missing                                                                                                                               | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | VehicleDetail     | Imported                |                    |        | null                                                                                                                                  | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | VehicleDetail     | Imported                |                    |        | ""                                                                                                                                    | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | VehicleDetail     | Imported                |                    |        | missing                                                                                                                               | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | VehicleDetail     | Imported                |                    |        | 0                                                                                                                                     | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | VehicleDetail     | Imported                |                    |        | 1                                                                                                                                     | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | VehicleDetail     | Imported                |                    |        | 2                                                                                                                                     | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | VehicleDetail     | SideCar                 |                    |        | TRUE                                                                                                                                  | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | VehicleDetail     | SideCar                 |                    |        | FALSE                                                                                                                                 | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | VehicleDetail     | SideCar                 |                    |        | null                                                                                                                                  | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | VehicleDetail     | SideCar                 |                    |        | ""                                                                                                                                    | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | VehicleDetail     | SideCar                 |                    |        | missing                                                                                                                               | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | VehicleDetail     | AccessoriesValue        |                    |        | 0                                                                                                                                     | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | VehicleDetail     | AccessoriesValue        |                    |        | null                                                                                                                                  | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | VehicleDetail     | AccessoriesValue        |                    |        | ""                                                                                                                                    | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | VehicleDetail     | AccessoriesValue        |                    |        | missing                                                                                                                               | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | VehicleDetail     | AccessoriesValue        |                    |        | 123                                                                                                                                   | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | AdditionalDrivers | DrivingLicenceNumber    |                    |        | null                                                                                                                                  | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | AdditionalDrivers | DrivingLicenceNumber    |                    |        | ""                                                                                                                                    | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | AdditionalDrivers | DrivingLicenceNumber    |                    |        | missing                                                                                                                               | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | AdditionalDrivers | DrivingLicenceNumber    |                    |        | 123                                                                                                                                   | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | AdditionalDrivers | NonRTAConviction        |                    |        | FALSE                                                                                                                                 | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | AdditionalDrivers | NonRTAConviction        |                    |        | null                                                                                                                                  | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | AdditionalDrivers | NonRTAConviction        |                    |        | ""                                                                                                                                    | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | AdditionalDrivers | NonRTAConviction        |                    |        | missing                                                                                                                               | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | AdditionalDrivers | BankRuptOrCcJ           |                    |        | TRUE                                                                                                                                  | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | AdditionalDrivers | BankRuptOrCcJ           |                    |        | FALSE                                                                                                                                 | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | AdditionalDrivers | BankRuptOrCcJ           |                    |        | null                                                                                                                                  | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | AdditionalDrivers | BankRuptOrCcJ           |                    |        | ""                                                                                                                                    | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | Vehicle                     | AdditionalDrivers | BankRuptOrCcJ           |                    |        | missing                                                                                                                               | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | AutoRenewal                 |                   |                         |                    |        | TRUE                                                                                                                                  | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | AutoRenewal                 |                   |                         |                    |        | FALSE                                                                                                                                 | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | AutoRenewal                 |                   |                         |                    |        | null                                                                                                                                  | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | AutoRenewal                 |                   |                         |                    |        | ""                                                                                                                                    | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | AutoRenewal                 |                   |                         |                    |        | missing                                                                                                                               | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | PolicyComment               |                   |                         |                    |        | null                                                                                                                                  | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | PolicyComment               |                   |                         |                    |        | ""                                                                                                                                    | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | PolicyComment               |                   |                         |                    |        | missing                                                                                                                               | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | PolicyComment               |                   |                         |                    |        | 123                                                                                                                                   | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Product               | PolicyMemo                  |                   |                         |                    |        | null                                                                                                                                  | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | PolicyMemo                  |                   |                         |                    |        | ""                                                                                                                                    | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | PolicyMemo                  |                   |                         |                    |        | missing                                                                                                                               | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | PolicyMemo                  |                   |                         |                    |        | 123                                                                                                                                   | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | PromoCode                   |                   |                         |                    |        | null                                                                                                                                  | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | PromoCode                   |                   |                         |                    |        | ""                                                                                                                                    | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | PromoCode                   |                   |                         |                    |        | missing                                                                                                                               | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | PromoCode                   | Added             |                         |                    |        | null                                                                                                                                  | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | PromoCode                   | Added             |                         |                    |        | ""                                                                                                                                    | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | PromoCode                   | Added             |                         |                    |        | missing                                                                                                                               | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | PromoCode                   | Added             |                         |                    |        | 123                                                                                                                                   | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | PromoCode                   | Code              |                         |                    |        | ""                                                                                                                                    | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | PromoCode                   | Code              |                         |                    |        | 123                                                                                                                                   | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Product               | PromoCode                   | Description       |                         |                    |        | null                                                                                                                                  | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | PromoCode                   | Description       |                         |                    |        | ""                                                                                                                                    | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | PromoCode                   | Description       |                         |                    |        | missing                                                                                                                               | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | PromoCode                   | Description       |                         |                    |        | 123                                                                                                                                   | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | PromoCode                   | Effective         |                         |                    |        | null                                                                                                                                  | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | PromoCode                   | Effective         |                         |                    |        | ""                                                                                                                                    | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | PromoCode                   | Effective         |                         |                    |        | 123                                                                                                                                   | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | PromoCode                   | Effective         |                         |                    |        | missing                                                                                                                               | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | PromoCode                   | Obsolete          |                         |                    |        | null                                                                                                                                  | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | PromoCode                   | Obsolete          |                         |                    |        | ""                                                                                                                                    | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | PromoCode                   | Obsolete          |                         |                    |        | missing                                                                                                                               | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | PromoCode                   | Obsolete          |                         |                    |        | 123                                                                                                                                   | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | PromoCode                   | Process           |                         |                    |        | null                                                                                                                                  | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | PromoCode                   | Process           |                         |                    |        | ""                                                                                                                                    | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | PromoCode                   | Process           |                         |                    |        | missing                                                                                                                               | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | PromoCode                   | Process           |                         |                    |        | 123                                                                                                                                   | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | PolicyInceptionDate         |                   |                         |                    |        | null                                                                                                                                  | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | PolicyInceptionDate         |                   |                         |                    |        | ""                                                                                                                                    | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | PolicyInceptionDate         |                   |                         |                    |        | missing                                                                                                                               | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | PolicyInceptionDate         |                   |                         |                    |        | 2020-09-15T00:00:00                                                                                                                   | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Product               | PolicyInceptionTime         |                   |                         |                    |        | null                                                                                                                                  | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | PolicyInceptionTime         |                   |                         |                    |        | ""                                                                                                                                    | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | PolicyInceptionTime         |                   |                         |                    |        | missing                                                                                                                               | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | PolicyInceptionTime         |                   |                         |                    |        | 01:00                                                                                                                                 | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Product               | PolicytTargetPremium        |                   |                         |                    |        | null                                                                                                                                  | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | PolicytTargetPremium        |                   |                         |                    |        | ""                                                                                                                                    | 200        | TRUE      | Store partial quote successfully |
	| Risk   | Product               | PolicytTargetPremium        |                   |                         |                    |        | missing                                                                                                                               | 200        | true      | Store partial quote successfully |
	| Risk   | Product               | PolicytTargetPremium        |                   |                         |                    |        | 123                                                                                                                                   | 200        | TRUE      | Store partial quote successfully |