// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AtlantaApi.Feature.ScenicMH.WebHookService.V1
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "ScenicMH")]
    public partial class SendARequestWithValidEndpointURLMethodForScenicMHInstalmentsFeature : object, Xunit.IClassFixture<SendARequestWithValidEndpointURLMethodForScenicMHInstalmentsFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = new string[] {
                "ScenicMH"};
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "PaymentOutcomeNormalCaseInstalmns.feature"
#line hidden
        
        public SendARequestWithValidEndpointURLMethodForScenicMHInstalmentsFeature(SendARequestWithValidEndpointURLMethodForScenicMHInstalmentsFeature.FixtureData fixtureData, AtlantaApi_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Feature/ScenicMH/WebHookService/V1", "Send a request with valid endpoint URL & method for ScenicMH Instalments", null, ProgrammingLanguage.CSharp, new string[] {
                        "ScenicMH"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Send a request with valid endpoint URL & method for ScenicMH")]
        [Xunit.TraitAttribute("FeatureTitle", "Send a request with valid endpoint URL & method for ScenicMH Instalments")]
        [Xunit.TraitAttribute("Description", "Send a request with valid endpoint URL & method for ScenicMH")]
        [Xunit.TraitAttribute("Category", "WebhookServices")]
        [Xunit.InlineDataAttribute("200", "/mh/newbus/confirmation?", new string[0])]
        public virtual void SendARequestWithValidEndpointURLMethodForScenicMH(string statusCode, string messages, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "WebhookServices"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("StatusCode", statusCode);
            argumentsOfScenario.Add("Messages", messages);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Send a request with valid endpoint URL & method for ScenicMH", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 5
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table501 = new TechTalk.SpecFlow.Table(new string[] {
                            "Property",
                            "Value"});
                table501.AddRow(new string[] {
                            "Uri",
                            "/api/V1/payment/outcome/at//sw//sc//mh//SWIN"});
                table501.AddRow(new string[] {
                            "WebHookBody",
                            "WebHookBodyScenicMH.json"});
                table501.AddRow(new string[] {
                            "QuoteRequestBody",
                            "ValidQuoteForScenicMHWebHook.json"});
                table501.AddRow(new string[] {
                            "PaymentRequestBody",
                            "RegisterPaymentRequestBodyScenicMH.json"});
                table501.AddRow(new string[] {
                            "SaveDebitRequestBody",
                            "SaveDebitRequestBodyScenicMH.json"});
                table501.AddRow(new string[] {
                            "SaveMarketingRequestBody",
                            "SaveMarketingRequestBodyScenicMH.json"});
                table501.AddRow(new string[] {
                            "SavePaymentInfoRequestBody",
                            "SavePaymentInfoRequestBodyInstalmntsScenicMH.json"});
                table501.AddRow(new string[] {
                            "SaveCardConsentBody",
                            "SaveCardConsentBodyScenicMH.json"});
                table501.AddRow(new string[] {
                            "ApiVersion",
                            "V2"});
                table501.AddRow(new string[] {
                            "ContextName",
                            "ScenicMotorHome"});
#line 6
 testRunner.Given("I have wrapUp table", ((string)(null)), table501, "Given ");
#line hidden
#line 19
 testRunner.When("User send a Register Instalments Payment service", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 20
 testRunner.And("User send a WebHook service", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 21
 testRunner.Then(string.Format("Payment response returns {0} and {1}", statusCode, messages), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                SendARequestWithValidEndpointURLMethodForScenicMHInstalmentsFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                SendARequestWithValidEndpointURLMethodForScenicMHInstalmentsFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
