// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AtlantaApi.Feature.SafeGuard.QuoteService.PartialQuote.V2
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "SafeGuardMH")]
    public partial class PartialQuoteSingleFieldDataValidationCasesPart3Feature : object, Xunit.IClassFixture<PartialQuoteSingleFieldDataValidationCasesPart3Feature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = new string[] {
                "SafeGuardMH"};
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "PartialQuoteSingleFieldDataValidationPart3.feature"
#line hidden
        
        public PartialQuoteSingleFieldDataValidationCasesPart3Feature(PartialQuoteSingleFieldDataValidationCasesPart3Feature.FixtureData fixtureData, AtlantaApi_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Feature/SafeGuard/QuoteService/PartialQuote/V2", "PartialQuoteSingleFieldDataValidationCasesPart3", null, ProgrammingLanguage.CSharp, new string[] {
                        "SafeGuardMH"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="ValiDate Partial quote API on each field")]
        [Xunit.TraitAttribute("FeatureTitle", "PartialQuoteSingleFieldDataValidationCasesPart3")]
        [Xunit.TraitAttribute("Description", "ValiDate Partial quote API on each field")]
        [Xunit.TraitAttribute("Category", "QuoteServices")]
        [Xunit.InlineDataAttribute("Risk", "Product", "Vehicle", "VehicleDetail", "Seats", "", "", "\"\"", "400", "FALSE", "Seats is required.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Vehicle", "VehicleDetail", "Seats", "", "", "null", "400", "FALSE", "Seats is required.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Vehicle", "VehicleDetail", "Seats", "", "", "missing", "400", "FALSE", "Seats is required.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Vehicle", "VehicleDetail", "HandednessDrivingType", "", "", "\"\"", "400", "FALSE", "HandednessDrivingType is required.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Vehicle", "VehicleDetail", "HandednessDrivingType", "", "", "null", "400", "FALSE", "HandednessDrivingType is required.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Vehicle", "VehicleDetail", "HandednessDrivingType", "", "", "missing", "400", "FALSE", "HandednessDrivingType is required.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Vehicle", "VehicleDetail", "HandednessDrivingType", "", "", "abc", "400", "FALSE", "HandednessDrivingType is invalid", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Vehicle", "VehicleDetail", "DatePurchased", "", "", "\"\"", "400", "FALSE", "DatePurchased is required.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Vehicle", "VehicleDetail", "DatePurchased", "", "", "null", "400", "FALSE", "DatePurchased is required.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Vehicle", "VehicleDetail", "DatePurchased", "", "", "missing", "400", "FALSE", "DatePurchased is required.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Vehicle", "VehicleDetail", "Owner", "", "", "null", "400", "FALSE", "Owner is required.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Vehicle", "VehicleDetail", "Owner", "", "", "missing", "400", "FALSE", "Owner is required.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Vehicle", "VehicleDetail", "Owner", "", "", "\"\"", "400", "FALSE", "Owner is required.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Vehicle", "VehicleDetail", "RegisteredKeeper", "", "", "\"\"", "400", "FALSE", "RegisteredKeeper is required.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Vehicle", "VehicleDetail", "RegisteredKeeper", "", "", "null", "400", "FALSE", "RegisteredKeeper is required.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Vehicle", "VehicleDetail", "RegisteredKeeper", "", "", "missing", "400", "FALSE", "RegisteredKeeper is required.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Vehicle", "VehicleDetail", "LocationParkedOvernight", "", "", "\"\"", "400", "FALSE", "LocationParkedOvernight is required.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Vehicle", "VehicleDetail", "LocationParkedOvernight", "", "", "null", "400", "FALSE", "LocationParkedOvernight is required.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Vehicle", "VehicleDetail", "LocationParkedOvernight", "", "", "missing", "400", "FALSE", "LocationParkedOvernight is required.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Vehicle", "VehicleDetail", "PostCodeParkedOvernight", "", "", "\"\"", "400", "FALSE", "PostCodeParkedOvernight is required.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Vehicle", "VehicleDetail", "PostCodeParkedOvernight", "", "", "null", "400", "FALSE", "PostCodeParkedOvernight is required.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Vehicle", "VehicleDetail", "PostCodeParkedOvernight", "", "", "missing", "400", "FALSE", "PostCodeParkedOvernight is required.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Vehicle", "VehicleDetail", "PostCodeParkedOvernight", "", "", "abcdfdd", "400", "FALSE", "PostCodeParkedOvernight is incorrect.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Vehicle", "VehicleDetail", "ClassOfUse", "", "", "\"\"", "400", "FALSE", "ClassOfUse is required.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Vehicle", "VehicleDetail", "ClassOfUse", "", "", "null", "400", "FALSE", "ClassOfUse is required.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Vehicle", "VehicleDetail", "ClassOfUse", "", "", "missing", "400", "FALSE", "ClassOfUse is required.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Vehicle", "VehicleDetail", "Mileage", "", "", "File: VehicleDetailMileage871.json", "400", "FALSE", "At least one mileage element must be added.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Vehicle", "VehicleDetail", "Mileage", "", "", "missing", "400", "FALSE", "At least one mileage element must be added.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Vehicle", "VehicleDetail", "Mileage", "", "", "null", "400", "FALSE", "At least one mileage element must be added.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Vehicle", "VehicleDetail", "Mileage", "Type", "", "\"\"", "400", "FALSE", "Mileage - Type is required.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Vehicle", "VehicleDetail", "Mileage", "Type", "", "null", "400", "FALSE", "Mileage - Type is required.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Vehicle", "VehicleDetail", "Mileage", "Type", "", "missing", "400", "FALSE", "Mileage - Type is required.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Vehicle", "VehicleDetail", "Mileage", "Type", "", "Test", "400", "FALSE", "Mileage - Type is invalid.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Vehicle", "VehicleDetail", "Mileage", "Value", "", "\"\"", "400", "FALSE", "Mileage - Value is required.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Vehicle", "VehicleDetail", "Mileage", "Value", "", "null", "400", "FALSE", "Mileage - Value is required.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Vehicle", "VehicleDetail", "Mileage", "Value", "", "missing", "400", "FALSE", "Mileage - Value is required.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Vehicle", "VehicleDetail", "Mileage", "Value", "", "99", "400", "FALSE", "Mileage - Value must be a number from 100 ~ 999999.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Vehicle", "VehicleDetail", "Mileage", "Value", "", "1000000", "400", "FALSE", "Mileage - Value must be a number from 100 ~ 999999.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Vehicle", "VehicleDetail", "Mileage", "Value", "", "abc", "400", "FALSE", "Mileage - Value must be a number from 100 ~ 999999.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Vehicle", "VehicleDetail", "CurrentValue", "", "", "\"\"", "400", "FALSE", "CurrentValue is required.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Vehicle", "VehicleDetail", "CurrentValue", "", "", "null", "400", "FALSE", "CurrentValue is required.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Vehicle", "VehicleDetail", "CurrentValue", "", "", "missing", "400", "FALSE", "CurrentValue is required.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Vehicle", "VehicleDetail", "CurrentValue", "", "", "-1", "400", "FALSE", "CurrentValue must be a positive number from 0 ~ 999999.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Vehicle", "VehicleDetail", "PurchasePrice", "", "", "\"\"", "400", "FALSE", "PurchasePrice is required.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Vehicle", "VehicleDetail", "PurchasePrice", "", "", "null", "400", "FALSE", "PurchasePrice is required.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Vehicle", "VehicleDetail", "PurchasePrice", "", "", "missing", "400", "FALSE", "PurchasePrice is required.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Vehicle", "VehicleDetail", "MainDriverId", "", "", "\"\"", "400", "FALSE", "MainDriverId is required.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Vehicle", "VehicleDetail", "MainDriverId", "", "", "null", "400", "FALSE", "MainDriverId is required.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Vehicle", "VehicleDetail", "MainDriverId", "", "", "missing", "400", "FALSE", "MainDriverId is required.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Vehicle", "VehicleDetail", "MainDriverId", "", "", "10", "400", "FALSE", "MainDriverId does not match any driver in request.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "WebReference", "", "", "", "", "", "435-444-xxx-543", "400", "FALSE", "WebReference is invalid.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "PolicyStartDate", "", "", "", "", "2020-09-16T00:00:00", "400", "FALSE", "PolicyStartDate cannot be in the past.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "PolicyStartDate", "", "", "", "", "null", "200", "ByPass", "", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "PolicyStartDate", "", "", "", "", "\"\"", "200", "ByPass", "", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "VoluntaryExcess", "", "", "", "", "-1", "400", "FALSE", "VoluntaryExcess must be integer greater than or equal 0.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "VoluntaryExcess", "", "", "", "", "3.14", "400", "FALSE", "VoluntaryExcess must be integer greater than or equal 0.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "VoluntaryExcess", "", "", "", "", "abc", "400", "FALSE", "VoluntaryExcess must be integer greater than or equal 0.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Claims", "", "", "", "", "File: ProductClaims929.json", "400", "FALSE", "Cannot quote for more than 5 claims.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Claims", "PersonId", "", "", "", "null", "400", "FALSE", "Error converting value {null} to type \'System.Int32\'. Path \'Risk.Product.Claims[0" +
            "].PersonId\'", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Claims", "PersonId", "", "", "", "\"\"", "400", "FALSE", "Error converting value {null} to type \'System.Int32\'. Path \'Risk.Product.Claims[0" +
            "].PersonId\'", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Claims", "PersonId", "", "", "", "missing", "400", "FALSE", "Claim - PersonId is required.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Claims", "PersonId", "", "", "", "15", "400", "FALSE", "Claim - PersonId does not match any driver in request.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Claims", "Code", "", "", "", "null", "400", "FALSE", "Claim - Code is required.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Claims", "Code", "", "", "", "\"\"", "400", "FALSE", "Claim - Code is required.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Claims", "Code", "", "", "", "missing", "400", "FALSE", "Claim - Code is required.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Claims", "Date", "", "", "", "2022-01-01", "400", "FALSE", "Claim - Date cannot be in future.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Claims", "NcbAffected", "", "", "", "null", "400", "FALSE", "Claim - NcbAffected is required", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Claims", "NcbAffected", "", "", "", "\"\"", "400", "FALSE", "Claim - NcbAffected is required", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Claims", "NcbAffected", "", "", "", "missing", "400", "FALSE", "Claim - NcbAffected is required", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Claims", "Costs", "", "", "", "-1", "400", "FALSE", "Claim - Costs must be integer greater than or equal 0.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Claims", "Costs", "", "", "", "missing", "400", "FALSE", "Claim - Costs must be integer greater than or equal 0.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Claims", "Costs", "", "", "", "abc", "400", "FALSE", "Claim - Costs must be integer greater than or equal 0.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Claims", "ThirdPartyCost", "", "", "", "-1", "400", "FALSE", "Claim - ThirdPartyCost must be integer greater than or equal 0.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Claims", "ThirdPartyCost", "", "", "", "3.14", "400", "FALSE", "Claim - ThirdPartyCost must be integer greater than or equal 0.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Claims", "ThirdPartyCost", "", "", "", "abc", "400", "FALSE", "Claim - ThirdPartyCost must be integer greater than or equal 0.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Convictions", "", "", "", "", "File: ProductConvictions954.json", "400", "FALSE", "Cannot quote for more than 5 Convictions.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Convictions", "PersonId", "", "", "", "null", "400", "FALSE", "Error converting value {null} to type \'System.Int32\'. Path \'Risk.Product.Convicti" +
            "ons[0].PersonId\'", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Convictions", "PersonId", "", "", "", "\"\"", "400", "FALSE", "Error converting value {null} to type \'System.Int32\'. Path \'Risk.Product.Convicti" +
            "ons[0].PersonId\'", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Convictions", "PersonId", "", "", "", "missing", "400", "FALSE", "Conviction - PersonId is required.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Convictions", "PersonId", "", "", "", "15", "400", "FALSE", "Conviction - PersonId does not match any driver in request.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Convictions", "Code", "", "", "", "null", "400", "FALSE", "Conviction - Code is required.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Convictions", "Code", "", "", "", "\"\"", "400", "FALSE", "Conviction - Code is required.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Convictions", "Code", "", "", "", "missing", "400", "FALSE", "Conviction - Code is required.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Convictions", "Date", "", "", "", "2022-01-01", "400", "FALSE", "Conviction - Date cannot be in future.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Convictions", "BanLength", "", "", "", "-1", "400", "FALSE", "Conviction - BanLength must be integer greater than or equal 0.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Convictions", "BanLength", "", "", "", "3.14", "400", "FALSE", "Conviction - BanLength must be integer greater than or equal 0.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Convictions", "BanLength", "", "", "", "abc", "400", "FALSE", "Conviction - BanLength must be integer greater than or equal 0.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Convictions", "FineAmount", "", "", "", "-1", "400", "FALSE", "Conviction - FineAmount must be integer greater than or equal 0.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Convictions", "FineAmount", "", "", "", "3.14", "400", "FALSE", "Conviction - FineAmount must be integer greater than or equal 0.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Convictions", "FineAmount", "", "", "", "abc", "400", "FALSE", "Conviction - FineAmount must be integer greater than or equal 0.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Convictions", "PenaltyPoints", "", "", "", "-1", "400", "FALSE", "Conviction - PenaltyPoints must be integer greater than or equal 0.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Convictions", "PenaltyPoints", "", "", "", "3.14", "400", "FALSE", "Conviction - PenaltyPoints must be integer greater than or equal 0.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Convictions", "PenaltyPoints", "", "", "", "abc", "400", "FALSE", "Conviction - PenaltyPoints must be integer greater than or equal 0.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Convictions", "DrinkReading", "", "", "", "AB", "400", "FALSE", "DrinkReading is invalid.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Convictions", "DrinkReadingLevel", "", "", "", "251", "400", "FALSE", "DrinkReadingLevel must be from 0 ~ 250.", new string[0])]
        public virtual void ValiDatePartialQuoteAPIOnEachField(string level1, string level2, string level3, string level4, string level5, string level6, string level7, string value, string statusCode, string isSuccess, string message, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "QuoteServices"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Level1", level1);
            argumentsOfScenario.Add("Level2", level2);
            argumentsOfScenario.Add("Level3", level3);
            argumentsOfScenario.Add("Level4", level4);
            argumentsOfScenario.Add("Level5", level5);
            argumentsOfScenario.Add("Level6", level6);
            argumentsOfScenario.Add("Level7", level7);
            argumentsOfScenario.Add("Value", value);
            argumentsOfScenario.Add("StatusCode", statusCode);
            argumentsOfScenario.Add("IsSuccess", isSuccess);
            argumentsOfScenario.Add("Message", message);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ValiDate Partial quote API on each field", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table383 = new TechTalk.SpecFlow.Table(new string[] {
                            "Name",
                            "Value1"});
                table383.AddRow(new string[] {
                            "Url",
                            "PartialQuote"});
                table383.AddRow(new string[] {
                            "ApiVersion",
                            "V2"});
                table383.AddRow(new string[] {
                            "Context",
                            "SafeGuardMH"});
                table383.AddRow(new string[] {
                            "JsonBodyFile",
                            "ValidQuoteForSGGetQuote.json"});
#line 7
 testRunner.Given("The customer has", ((string)(null)), table383, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table384 = new TechTalk.SpecFlow.Table(new string[] {
                            "Level1",
                            "Level2",
                            "Level3",
                            "Level4",
                            "Level5",
                            "Level6",
                            "Level7",
                            "Value"});
                table384.AddRow(new string[] {
                            string.Format("{0}", level1),
                            string.Format("{0}", level2),
                            string.Format("{0}", level3),
                            string.Format("{0}", level4),
                            string.Format("{0}", level5),
                            string.Format("{0}", level6),
                            string.Format("{0}", level7),
                            string.Format("{0}", value)});
#line 13
 testRunner.When("The customer call quote API", ((string)(null)), table384, "When ");
#line hidden
#line 16
 testRunner.Then(string.Format("The message should be shown {0},{1},\"{2}\"", statusCode, isSuccess, message), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                PartialQuoteSingleFieldDataValidationCasesPart3Feature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                PartialQuoteSingleFieldDataValidationCasesPart3Feature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
