// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AtlantaApi.Feature.CNBike.WebHookService.V1
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "CNBike")]
    public partial class PaymentOutcomeValidationFeature : object, Xunit.IClassFixture<PaymentOutcomeValidationFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = new string[] {
                "CNBike"};
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "PaymentOutcomeValidation.feature"
#line hidden
        
        public PaymentOutcomeValidationFeature(PaymentOutcomeValidationFeature.FixtureData fixtureData, AtlantaApi_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Feature/CNBike/WebHookService/V1", "PaymentOutcomeValidation", null, ProgrammingLanguage.CSharp, new string[] {
                        "CNBike"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="PaymentOutcomeValidation")]
        [Xunit.TraitAttribute("FeatureTitle", "PaymentOutcomeValidation")]
        [Xunit.TraitAttribute("Description", "PaymentOutcomeValidation")]
        [Xunit.TraitAttribute("Category", "WebhookServices")]
        [Xunit.InlineDataAttribute("AmountPaid", "302", "200", "/mc/confirmation", new string[0])]
        [Xunit.InlineDataAttribute("PaymentType", "\"\"", "200", "/mc/confirmation", new string[0])]
        [Xunit.InlineDataAttribute("CardTypeCode", "2", "200", "/mc/confirmation", new string[0])]
        [Xunit.InlineDataAttribute("CardTypeValue", "missing", "200", "/mc/confirmation", new string[0])]
        [Xunit.InlineDataAttribute("CardTypeValue", "Mastercard", "200", "/mc/confirmation", new string[0])]
        [Xunit.InlineDataAttribute("CardFee", "missing", "200", "/mc/confirmation", new string[0])]
        [Xunit.InlineDataAttribute("CardFee", "50000", "200", "/mc/confirmation", new string[0])]
        [Xunit.InlineDataAttribute("CardHolderName", "Test", "200", "/mc/confirmation", new string[0])]
        [Xunit.InlineDataAttribute("ExpiryMonth", "1", "200", "/mc/confirmation", new string[0])]
        [Xunit.InlineDataAttribute("ExpiryYear", "2040", "200", "/mc/confirmation", new string[0])]
        [Xunit.InlineDataAttribute("IIN", "missing", "200", "/mc/confirmation", new string[0])]
        [Xunit.InlineDataAttribute("IIN", "545454", "200", "/mc/confirmation", new string[0])]
        [Xunit.InlineDataAttribute("IssueNumber", "556", "200", "/mc/confirmation", new string[0])]
        [Xunit.InlineDataAttribute("MaskedCardNumber", "1234", "200", "/mc/confirmation", new string[0])]
        [Xunit.InlineDataAttribute("PreviousTransactionDate", "missing", "200", "/mc/confirmation", new string[0])]
        [Xunit.InlineDataAttribute("PreviousTransactionId", "missing", "200", "/mc/confirmation", new string[0])]
        [Xunit.InlineDataAttribute("StartMonth", "2", "200", "/mc/confirmation", new string[0])]
        [Xunit.InlineDataAttribute("StartYear", "2019", "200", "/mc/confirmation", new string[0])]
        public virtual void PaymentOutcomeValidation(string level1, string value, string statusCode, string message, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "WebhookServices"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Level1", level1);
            argumentsOfScenario.Add("Value", value);
            argumentsOfScenario.Add("StatusCode", statusCode);
            argumentsOfScenario.Add("Message", message);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PaymentOutcomeValidation", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 5
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table277 = new TechTalk.SpecFlow.Table(new string[] {
                            "Property",
                            "Value"});
                table277.AddRow(new string[] {
                            "Uri",
                            "/api/V1/payment/outcome/atlantaBrandCode//Carolenash//Carolenash//motorbike//6270" +
                                ""});
                table277.AddRow(new string[] {
                            "WebHookBody",
                            "WebHookBodyCNBike.json"});
                table277.AddRow(new string[] {
                            "QuoteRequestBody",
                            "ValidQuoteForRegisterPaymentCNBike.json"});
                table277.AddRow(new string[] {
                            "PaymentRequestBody",
                            "RegisterPaymentRequestBodyCNBike.json"});
                table277.AddRow(new string[] {
                            "SaveDebitRequestBody",
                            "SaveDebitRequestBodyCNBike.json"});
                table277.AddRow(new string[] {
                            "SaveMarketingRequestBody",
                            "SaveMarketingRequestBodyCNBike.json"});
                table277.AddRow(new string[] {
                            "SavePaymentInfoRequestBody",
                            "SavePaymentInfoRequestBodyCNBike.json"});
                table277.AddRow(new string[] {
                            "ApiVersion",
                            "V1"});
                table277.AddRow(new string[] {
                            "ContextName",
                            "CNBikeContext"});
#line 6
 testRunner.Given("I have wrapUp table", ((string)(null)), table277, "Given ");
#line hidden
#line 18
 testRunner.When("User send a Register PayInFull Payment service", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table278 = new TechTalk.SpecFlow.Table(new string[] {
                            "Level1",
                            "Value"});
                table278.AddRow(new string[] {
                            string.Format("{0}", level1),
                            string.Format("{0}", value)});
#line 19
 testRunner.And("User send a WebHook service with", ((string)(null)), table278, "And ");
#line hidden
#line 22
 testRunner.Then(string.Format("Payment response returns {0} and {1}", statusCode, message), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="PaymentOutcomeValidationsStartYear")]
        [Xunit.TraitAttribute("FeatureTitle", "PaymentOutcomeValidation")]
        [Xunit.TraitAttribute("Description", "PaymentOutcomeValidationsStartYear")]
        [Xunit.TraitAttribute("Category", "WebhookServices")]
        [Xunit.InlineDataAttribute("StartYear", "missing", "200", "/mc/confirmation", new string[0])]
        public virtual void PaymentOutcomeValidationsStartYear(string level1, string value, string statusCode, string message, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "WebhookServices"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Level1", level1);
            argumentsOfScenario.Add("Value", value);
            argumentsOfScenario.Add("StatusCode", statusCode);
            argumentsOfScenario.Add("Message", message);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PaymentOutcomeValidationsStartYear", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 45
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table279 = new TechTalk.SpecFlow.Table(new string[] {
                            "Property",
                            "Value"});
                table279.AddRow(new string[] {
                            "Uri",
                            "/api/V1/payment/outcome/atlantaBrandCode//Carolenash//Carolenash//motorbike//6270" +
                                ""});
                table279.AddRow(new string[] {
                            "WebHookBody",
                            "WebHookBodyMissingStartMonthCNBike.json"});
                table279.AddRow(new string[] {
                            "QuoteRequestBody",
                            "ValidQuoteForRegisterPaymentCNBike.json"});
                table279.AddRow(new string[] {
                            "PaymentRequestBody",
                            "RegisterPaymentRequestBodyCNBike.json"});
                table279.AddRow(new string[] {
                            "SaveDebitRequestBody",
                            "SaveDebitRequestBodyCNBike.json"});
                table279.AddRow(new string[] {
                            "SaveMarketingRequestBody",
                            "SaveMarketingRequestBodyCNBike.json"});
                table279.AddRow(new string[] {
                            "SavePaymentInfoRequestBody",
                            "SavePaymentInfoRequestBodyCNBike.json"});
                table279.AddRow(new string[] {
                            "ApiVersion",
                            "V1"});
                table279.AddRow(new string[] {
                            "ContextName",
                            "CNBikeContext"});
#line 46
 testRunner.Given("I have wrapUp table", ((string)(null)), table279, "Given ");
#line hidden
#line 58
 testRunner.When("User send a Register PayInFull Payment service", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table280 = new TechTalk.SpecFlow.Table(new string[] {
                            "Level1",
                            "Value"});
                table280.AddRow(new string[] {
                            string.Format("{0}", level1),
                            string.Format("{0}", value)});
#line 59
 testRunner.And("User send a WebHook service with", ((string)(null)), table280, "And ");
#line hidden
#line 62
 testRunner.Then(string.Format("Payment response returns {0} and {1}", statusCode, message), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                PaymentOutcomeValidationFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                PaymentOutcomeValidationFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
