#Cover 471 cases
@ScenicMH
Feature: PartialQuoteSingleFieldDataValidationCasesPart1

@QuoteServices
Scenario Outline: ValiDate Partial quote API on each field
	Given The customer has 
	| Name         | Value1                             |
	| Url          | PartialQuote                       |
	| ApiVersion   | V2                                 |
	| Context      | ScenicMotorHome                    |
	| JsonBodyFile | ValidQuoteForScenicMHGetQuote.json |
	When The customer call quote API
		| Level1   | Level2   | Level3   | Level4   | Level5   | Level6   | Level7   | Value   |
		| <Level1> | <Level2> | <Level3> | <Level4> | <Level5> | <Level6> | <Level7> | <Value> |
	Then The message should be shown <StatusCode>,<IsSuccess>,"<Message>"
	Examples:	
	| Level1 | Level2   | Level3              | Level4         | Level5 | Level6 | Level7 | Value                                                                                                                                 | StatusCode | IsSuccess | Message                                                                    |
	| Risk   | Proposer | Id                  |                |        |        |        | null                                                                                                                                  | 400        | FALSE     | Proposer must be 1. |
	| Risk   | Proposer | Id                  |                |        |        |        | 2                                                                                                                                     | 400        | FALSE     | Proposer must be 1.                                                        |
	| Risk   | Proposer | Id                  |                |        |        |        | missing                                                                                                                               | 400        | FALSE     | Proposer must be 1.                                                        |
	| Risk   | Proposer | Salutation          |                |        |        |        | null                                                                                                                                  | 400        | FALSE     | Salutation is required.                                                    |
	| Risk   | Proposer | Salutation          |                |        |        |        | ""                                                                                                                                    | 400        | FALSE     | Salutation is required.                                                    |
	| Risk   | Proposer | Salutation          |                |        |        |        | missing                                                                                                                               | 400        | FALSE     | Salutation is required.                                                    |
	| Risk   | Proposer | Salutation          |                |        |        |        | Mrs Selena abcdfgtrgfdabcdfgtrgfdabcdfgtrgfdabcdfgtrgfdabcdfgtrgfdabcdfgtrgfdabcdfgtrgfdabcdfgtrgfdabcdfgtrgfdabcdfgtrgfdabcdfgtrgfdr | 400        | FALSE     | Salutation cannot be over 121 characters.                                  |
	| Risk   | Proposer | Title               |                |        |        |        | missing                                                                                                                               | 400        | FALSE     | Title is required.                                                         |
	| Risk   | Proposer | Title               |                |        |        |        | null                                                                                                                                  | 400        | FALSE     | Title is required.                                                         |
	| Risk   | Proposer | Title               |                |        |        |        | ""                                                                                                                                    | 400        | FALSE     | Title is required.                                                         |
	| Risk   | Proposer | Forenames           |                |        |        |        | missing                                                                                                                               | 400        | FALSE     | Forenames is required.                                                     |
	| Risk   | Proposer | Forenames           |                |        |        |        | null                                                                                                                                  | 400        | FALSE     | Forenames is required.                                                     |
	| Risk   | Proposer | Forenames           |                |        |        |        | ""                                                                                                                                    | 400        | FALSE     | Forenames is required.                                                     |
	| Risk   | Proposer | Forenames           |                |        |        |        | Selena Gomz qazxswedcrfvbgtyhnm                                                                                                       | 400        | FALSE     | Forenames cannot be over 30 characters.                                    |
	| Risk   | Proposer | Surname             |                |        |        |        | missing                                                                                                                               | 400        | FALSE     | Surname is required.                                                       |
	| Risk   | Proposer | Surname             |                |        |        |        | null                                                                                                                                  | 400        | FALSE     | Surname is required.                                                       |
	| Risk   | Proposer | Surname             |                |        |        |        | ""                                                                                                                                    | 400        | FALSE     | Surname is required.                                                       |
	| Risk   | Proposer | Surname             |                |        |        |        | Selena Gom Selena GomSelena GomSelena GomSelena GomSelena GomSelena GomSelena GomSelena Gom nkshfkhakfhkhafihia                       | 400        | FALSE     | Surname cannot be over 100 characters.                                     |
	| Risk   | Proposer | DateOfBirth         |                |        |        |        | missing                                                                                                                               | 400        | FALSE     | DateOfBirth is required.                                                   |
	| Risk   | Proposer | DateOfBirth         |                |        |        |        | null                                                                                                                                  | 400        | FALSE     | DateOfBirth is required.                                                   |
	| Risk   | Proposer | DateOfBirth         |                |        |        |        | ""                                                                                                                                    | 400        | FALSE     | DateOfBirth is required.                                                   |
	| Risk   | Proposer | UKResidentSinceDate |                |        |        |        | missing                                                                                                                               | 400        | FALSE     | UKResidentSinceDate is required.                                           |
	| Risk   | Proposer | UKResidentSinceDate |                |        |        |        | null                                                                                                                                  | 400        | FALSE     | UKResidentSinceDate is required.                                           |
	| Risk   | Proposer | UKResidentSinceDate |                |        |        |        | ""                                                                                                                                    | 400        | FALSE     | UKResidentSinceDate is required.                                           |
	| Risk   | Proposer | UKResidentSinceDate |                |        |        |        | 2021-12-16T00:00:00                                                                                                                   | 400        | FALSE     | UKResidentSinceDate cannot be in future.                                   |
	| Risk   | Proposer | MaritalStatus       |                |        |        |        | missing                                                                                                                               | 400        | FALSE     | MaritalStatus is required.                                                 |
	| Risk   | Proposer | MaritalStatus       |                |        |        |        | null                                                                                                                                  | 400        | FALSE     | MaritalStatus is required.                                                 |
	| Risk   | Proposer | MaritalStatus       |                |        |        |        | ""                                                                                                                                    | 400        | FALSE     | MaritalStatus is required.                                                 |
	| Risk   | Proposer | Employment          |                |        |        |        | missing                                                                                                                               | 400        | FALSE     | fulltime & parttime occupation are required.                               |
	| Risk   | Proposer | Employment          |                |        |        |        | null                                                                                                                                  | 400        | FALSE     | fulltime & parttime occupation are required.                               |
	| Risk   | Proposer | Employment          |                |        |        |        | File: ProposerEmployment602.json                                                                                                      | 400        | FALSE     | fulltime & parttime occupation are required.                               |
	| Risk   | Proposer | Employment          | Type           |        |        |        | missing                                                                                                                               | 400        | FALSE     | Employment - Typeis required.                                              |
	| Risk   | Proposer | Employment          | Type           |        |        |        | null                                                                                                                                  | 400        | FALSE     | Employment - Typeis required.                                              |
	| Risk   | Proposer | Employment          | Type           |        |        |        | ""                                                                                                                                    | 400        | FALSE     | Employment - Typeis required.                                              |
	| Risk   | Proposer | Employment          | Type           |        |        |        | Test                                                                                                                                  | 400        | FALSE     | Employment - Type must be fulltime/parttime.                               |
	| Risk   | Proposer | Employment          | EmploymentCode |        |        |        | missing                                                                                                                               | 400        | FALSE     | Employment - EmploymentCode is required.                                   |
	| Risk   | Proposer | Employment          | EmploymentCode |        |        |        | null                                                                                                                                  | 400        | FALSE     | Employment - EmploymentCode is required.                                   |
	| Risk   | Proposer | Employment          | EmploymentCode |        |        |        | ""                                                                                                                                    | 400        | FALSE     | Employment - EmploymentCode is required.                                   |
	| Risk   | Proposer | Employment          | OccupationCode |        |        |        | missing                                                                                                                               | 400        | FALSE     | Employment - OCcupationCode is required.                                   |
	| Risk   | Proposer | Employment          | OccupationCode |        |        |        | null                                                                                                                                  | 400        | FALSE     | Employment - OCcupationCode is required.                                   |
	| Risk   | Proposer | Employment          | OccupationCode |        |        |        | ""                                                                                                                                    | 400        | FALSE     | Employment - OCcupationCode is required.                                   |
	| Risk   | Proposer | Employment          | EmployerCode   |        |        |        | missing                                                                                                                               | 400        | FALSE     | Employment - EmployerCode is required.                                     |
	| Risk   | Proposer | Employment          | EmployerCode   |        |        |        | null                                                                                                                                  | 400        | FALSE     | Employment - EmployerCode is required.                                     |
	| Risk   | Proposer | Employment          | EmployerCode   |        |        |        | ""                                                                                                                                    | 400        | FALSE     | Employment - EmployerCode is required.                                     |
	| Risk   | Proposer | DrivingLicence      | Type           |        |        |        | missing                                                                                                                               | 400        | FALSE     | Driving Licence - Type is required.                                        |
	| Risk   | Proposer | DrivingLicence      | Type           |        |        |        | null                                                                                                                                  | 400        | FALSE     | Driving Licence - Type is required.                                        |
	| Risk   | Proposer | DrivingLicence      | Type           |        |        |        | ""                                                                                                                                    | 400        | FALSE     | Driving Licence - Type is required.                                        |
	| Risk   | Proposer | DrivingLicence      | DateObtained   |        |        |        | missing                                                                                                                               | 400        | FALSE     | Licence date is required.                                                  |
	| Risk   | Proposer | DrivingLicence      | DateObtained   |        |        |        | null                                                                                                                                  | 400        | FALSE     | Licence date is required.                                                  |
	| Risk   | Proposer | DrivingLicence      | DateObtained   |        |        |        | ""                                                                                                                                    | 400        | FALSE     | Licence date is required.                                                  |
	| Risk   | Proposer | DrivingLicence      | DateObtained   |        |        |        | 2021-12-16T00:00:00                                                                                                                   | 400        | FALSE     | Licence date cannot be future date.                                        |
	| Risk   | Proposer | PhoneNumbers        |                |        |        |        | missing                                                                                                                               | 400        | FALSE     | At least one Phone Number element is required.                             |
	| Risk   | Proposer | PhoneNumbers        |                |        |        |        | null                                                                                                                                  | 400        | FALSE     | At least one Phone Number element is required.                             |
	| Risk   | Proposer | PhoneNumbers        |                |        |        |        | File: ProposerPhoneNumbers637.json                                                                                                    | 400        | FALSE     | At least one Phone Number element is required.                             |
	| Risk   | Proposer | PhoneNumbers        | Type           |        |        |        | missing                                                                                                                               | 400        | FALSE     | PhoneNumber - Type is required.                                            |
	| Risk   | Proposer | PhoneNumbers        | Type           |        |        |        | null                                                                                                                                  | 400        | FALSE     | PhoneNumber - Type is required.                                            |
	| Risk   | Proposer | PhoneNumbers        | Type           |        |        |        | ""                                                                                                                                    | 400        | FALSE     | PhoneNumber - Type is required.                                            |
	| Risk   | Proposer | PhoneNumbers        | Number         |        |        |        | missing                                                                                                                               | 400        | FALSE     | PhoneNumber - Number is required.                                          |
	| Risk   | Proposer | PhoneNumbers        | Number         |        |        |        | null                                                                                                                                  | 400        | FALSE     | PhoneNumber - Number is required.                                          |
	| Risk   | Proposer | PhoneNumbers        | Number         |        |        |        | ""                                                                                                                                    | 400        | FALSE     | PhoneNumber - Number is required.                                          |
	| Risk   | Proposer | PhoneNumbers        | Number         |        |        |        | 12345678                                                                                                                              | 400        | FALSE     | PhoneNumber - Number must be from 9 ~ 14 characters.                       |
	| Risk   | Proposer | PhoneNumbers        | Number         |        |        |        | 123456789123456                                                                                                                       | 400        | FALSE     | PhoneNumber - Number must be from 9 ~ 14 characters.                       |
	| Risk   | Proposer | Address             | AddressLine1   |        |        |        | missing                                                                                                                               | 400        | FALSE     | AddressLine1 is required.                                                  |
	| Risk   | Proposer | Address             | AddressLine1   |        |        |        | null                                                                                                                                  | 400        | FALSE     | AddressLine1 is required.                                                  |
	| Risk   | Proposer | Address             | AddressLine1   |        |        |        | ""                                                                                                                                    | 400        | FALSE     | AddressLine1 is required.                                                  |
	| Risk   | Proposer | Address             | AddressLine1   |        |        |        | UK road 12UK road 12UK road 12123                                                                                                     | 400        | FALSE     | AddressLine1 cannot be over 32 characters.                                 |
	| Risk   | Proposer | Address             | AddressLine2   |        |        |        | missing                                                                                                                               | 400        | FALSE     | AddressLine2 is required.                                                  |
	| Risk   | Proposer | Address             | AddressLine2   |        |        |        | null                                                                                                                                  | 400        | FALSE     | AddressLine2 is required.                                                  |
	| Risk   | Proposer | Address             | AddressLine2   |        |        |        | ""                                                                                                                                    | 400        | FALSE     | AddressLine2 is required.                                                  |
	| Risk   | Proposer | Address             | AddressLine2   |        |        |        | UK road 12UK road 12UK road 12123                                                                                                     | 400        | FALSE     | AddressLine2 cannot be over 32 characters.                                 |
	| Risk   | Proposer | Address             | AddressLine3   |        |        |        | UK road 12UK road 12UK road 12123                                                                                                     | 400        | FALSE     | AddressLine3 cannot be over 32 characters.                                 |
	| Risk   | Proposer | Address             | AddressLine4   |        |        |        | UK road 12UK road 12UK road 12123                                                                                                     | 400        | FALSE     | AddressLine4 cannot be over 32 characters.                                 |
	| Risk   | Proposer | Address             | PostCode       |        |        |        | missing                                                                                                                               | 400        | FALSE     | PostCode is required.                                                      |
	| Risk   | Proposer | Address             | PostCode       |        |        |        | null                                                                                                                                  | 400        | FALSE     | PostCode is required.                                                      |
	| Risk   | Proposer | Address             | PostCode       |        |        |        | ""                                                                                                                                    | 400        | FALSE     | PostCode is required.                                                      |
	| Risk   | Proposer | Address             | PostCode       |        |        |        | EC2N 94AY                                                                                                                             | 400        | FALSE     | PostCode is invalid.                                                       |
	| Risk   | Proposer | EmailAddress        |                |        |        |        | missing                                                                                                                               | 400        | FALSE     | EmailAddress is required.                                                  |
	| Risk   | Proposer | EmailAddress        |                |        |        |        | null                                                                                                                                  | 400        | FALSE     | EmailAddress is required.                                                  |
	| Risk   | Proposer | EmailAddress        |                |        |        |        | ""                                                                                                                                    | 400        | FALSE     | EmailAddress is required.                                                  |
	| Risk   | Proposer | EmailAddress        |                |        |        |        | thuongnguyenthiminh@nashtech                                                                                                          | 400        | FALSE     | EmailAddress is invalid.                                                   |
	| Risk   | Proposer | Preferences         | Type           |        |        |        | missing                                                                                                                               | 400        | FALSE     | Preferences - Type is required.                                            |
	| Risk   | Proposer | Preferences         | Type           |        |        |        | null                                                                                                                                  | 400        | FALSE     | Preferences - Type is required.                                            |
	| Risk   | Proposer | Preferences         | Type           |        |        |        | ""                                                                                                                                    | 400        | FALSE     | Preferences - Type is required.                                            |
	| Risk   | Proposer | Preferences         | Type           |        |        |        | Test                                                                                                                                  | 400        | FALSE     | Preferences - Type is invalid.                                             |
	| Risk   | Proposer | Preferences         | SubType        |        |        |        | missing                                                                                                                               | 400        | FALSE     | Preferences - SubType is required.                                         |
	| Risk   | Proposer | Preferences         | SubType        |        |        |        | null                                                                                                                                  | 400        | FALSE     | Preferences - SubType is required.                                         |
	| Risk   | Proposer | Preferences         | SubType        |        |        |        | ""                                                                                                                                    | 400        | FALSE     | Preferences - SubType is required.                                         |
	| Risk   | Proposer | Preferences         | SubType        |        |        |        | Test                                                                                                                                  | 400        | FALSE     | Preferences - SubType is invalid.                                          |
	| Risk   | Proposer | Suffix              |                |        |        |        | Mrs Selenaz                                                                                                                           | 400        | FALSE     | suffix can not be over 10 characters.                                      |