// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AtlantaApi.Feature.ScenicMH.QuoteService.SaveMarketing.V1
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "ScenicMH")]
    public partial class ValidateSaveMarketingSingleFieldFeature : object, Xunit.IClassFixture<ValidateSaveMarketingSingleFieldFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = new string[] {
                "ScenicMH"};
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "SaveMarketingValidationCasesSingleField.feature"
#line hidden
        
        public ValidateSaveMarketingSingleFieldFeature(ValidateSaveMarketingSingleFieldFeature.FixtureData fixtureData, AtlantaApi_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Feature/ScenicMH/QuoteService/SaveMarketing/V1", "Validate Save Marketing Single Field", null, ProgrammingLanguage.CSharp, new string[] {
                        "ScenicMH"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Validate Save Marketing request with single fields")]
        [Xunit.TraitAttribute("FeatureTitle", "Validate Save Marketing Single Field")]
        [Xunit.TraitAttribute("Description", "Validate Save Marketing request with single fields")]
        [Xunit.TraitAttribute("Category", "QuoteServices")]
        [Xunit.InlineDataAttribute("SessionId", "null", "400", "false", "SessionId is required.", new string[0])]
        [Xunit.InlineDataAttribute("SessionId", "123456", "400", "false", "SessionId is invalid.", new string[0])]
        [Xunit.InlineDataAttribute("AgreementConfirmation", "missing", "200", "true", "Save data successfully", new string[0])]
        [Xunit.InlineDataAttribute("AgreementConfirmation", "null", "400", "false", "Error converting value {null} to type \'System.Boolean\'. Path \'AgreementConfirmati" +
            "on\'", new string[0])]
        [Xunit.InlineDataAttribute("AgreementConfirmation", "test", "400", "false", "Could not convert string to boolean: test. Path \'AgreementConfirmation\'", new string[0])]
        [Xunit.InlineDataAttribute("AgreementConfirmation", "true", "200", "true", "Save data successfully", new string[0])]
        [Xunit.InlineDataAttribute("PreferredDeliveryMethod", "null", "200", "true", "Save data successfully", new string[0])]
        [Xunit.InlineDataAttribute("PreferredDeliveryMethod", "Get", "400", "false", "PreferredDeliveryMethod is invalid.", new string[0])]
        [Xunit.InlineDataAttribute("PreferredDeliveryMethod", "Email", "200", "true", "Save data successfully", new string[0])]
        [Xunit.InlineDataAttribute("RegNumbers", "[]", "200", "true", "Save data successfully", new string[0])]
        [Xunit.InlineDataAttribute("RegNumbers", "null", "200", "true", "Save data successfully", new string[0])]
        [Xunit.InlineDataAttribute("Email", "null", "200", "true", "Save data successfully", new string[0])]
        [Xunit.InlineDataAttribute("Email", "jordan.knott@autonetinsurance.co.uk", "200", "true", "Save data successfully", new string[0])]
        [Xunit.InlineDataAttribute("Email", "jordan   knottautonetinsurance.co.uk", "400", "false", "Email is invalid.", new string[0])]
        [Xunit.InlineDataAttribute("PhoneNumber", "null", "200", "true", "Save data successfully", new string[0])]
        [Xunit.InlineDataAttribute("PhoneNumber", "078888888888888", "400", "false", "PhoneNumber must be from 9 ~ 14 characters.", new string[0])]
        [Xunit.InlineDataAttribute("PhoneNumber", "078888888888", "200", "true", "Save data successfully", new string[0])]
        [Xunit.InlineDataAttribute("GroupPartnerContact", "null", "200", "true", "Save data successfully", new string[0])]
        [Xunit.InlineDataAttribute("GroupPartnerContact", "Y", "200", "true", "Save data successfully", new string[0])]
        [Xunit.InlineDataAttribute("MarkTel", "null", "200", "true", "Save data successfully", new string[0])]
        [Xunit.InlineDataAttribute("MarkTel", "string", "200", "true", "Save data successfully", new string[0])]
        [Xunit.InlineDataAttribute("MarkSms", "null", "200", "true", "Save data successfully", new string[0])]
        [Xunit.InlineDataAttribute("MarkSms", "string", "200", "true", "Save data successfully", new string[0])]
        [Xunit.InlineDataAttribute("MarkEm", "null", "200", "true", "Save data successfully", new string[0])]
        [Xunit.InlineDataAttribute("MarkEm", "string", "200", "true", "Save data successfully", new string[0])]
        [Xunit.InlineDataAttribute("MarkP", "null", "200", "true", "Save data successfully", new string[0])]
        [Xunit.InlineDataAttribute("MarkP", "string", "200", "true", "Save data successfully", new string[0])]
        public virtual void ValidateSaveMarketingRequestWithSingleFields(string level1, string value, string statusCode, string isSuccess, string messages, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "QuoteServices"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Level1", level1);
            argumentsOfScenario.Add("Value", value);
            argumentsOfScenario.Add("StatusCode", statusCode);
            argumentsOfScenario.Add("IsSuccess", isSuccess);
            argumentsOfScenario.Add("Messages", messages);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Validate Save Marketing request with single fields", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table467 = new TechTalk.SpecFlow.Table(new string[] {
                            "Property",
                            "Value"});
                table467.AddRow(new string[] {
                            "SaveMarketingRequestBody",
                            "SaveMarketingRequestBodyScenicMH.json"});
                table467.AddRow(new string[] {
                            "QuoteRequestBody",
                            "ValidQuoteForScenicMH.json"});
                table467.AddRow(new string[] {
                            "ApiVersion",
                            "V2"});
                table467.AddRow(new string[] {
                            "ContextName",
                            "ScenicMotorHome"});
#line 7
 testRunner.Given("User has Save Marketing body", ((string)(null)), table467, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table468 = new TechTalk.SpecFlow.Table(new string[] {
                            "Level1",
                            "Value"});
                table468.AddRow(new string[] {
                            string.Format("{0}", level1),
                            string.Format("{0}", value)});
#line 13
 testRunner.When("User send Save Marketing request", ((string)(null)), table468, "When ");
#line hidden
#line 16
 testRunner.Then(string.Format("Save Marketing response returns {0} and {1} and {2}", statusCode, isSuccess, messages), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                ValidateSaveMarketingSingleFieldFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                ValidateSaveMarketingSingleFieldFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
