// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AtlantaApi.Feature.CNSelectedBike.QuoteService.SaveMarketing.V1
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "CNSBike")]
    public partial class ValidateSaveMarketingUsingInvalidIDAndVRNInfosFeature : object, Xunit.IClassFixture<ValidateSaveMarketingUsingInvalidIDAndVRNInfosFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = new string[] {
                "CNSBike"};
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "SaveMarketingInvalidRegNumberInfo.feature"
#line hidden
        
        public ValidateSaveMarketingUsingInvalidIDAndVRNInfosFeature(ValidateSaveMarketingUsingInvalidIDAndVRNInfosFeature.FixtureData fixtureData, AtlantaApi_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Feature/CNSelectedBike/QuoteService/SaveMarketing/V1", "Validate Save Marketing Using Invalid ID and VRN infos", null, ProgrammingLanguage.CSharp, new string[] {
                        "CNSBike"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Validate Save Marketing request with Invalid ID/VRN infos")]
        [Xunit.TraitAttribute("FeatureTitle", "Validate Save Marketing Using Invalid ID and VRN infos")]
        [Xunit.TraitAttribute("Description", "Validate Save Marketing request with Invalid ID/VRN infos")]
        [Xunit.TraitAttribute("Category", "QuoteServices")]
        [Xunit.InlineDataAttribute("5", "GX08NNT", "400", "false", "RegNumbers - Id must be 1 ~ 4 is invalid.", new string[0])]
        [Xunit.InlineDataAttribute("", "GX08NNT", "400", "false", "RegNumbers - Id is required.", new string[0])]
        [Xunit.InlineDataAttribute("1", "", "400", "false", "RegNumbers - Vrn is required.", new string[0])]
        [Xunit.InlineDataAttribute("1", "GBBD5I SM     R", "400", "false", "RegNumber - Vrn - GBBD5ISMR cannot be over 8 characters.", new string[0])]
        [Xunit.InlineDataAttribute("1", "Q874 9FP", "400", "false", "RegNumbers - Vrn with Q registration plate - Q8749FP is unacceptable.", new string[0])]
        [Xunit.InlineDataAttribute("1", "GX08NNT890123", "400", "false", "RegNumber - Vrn - GX08NNT890123 cannot be over 8 characters.", new string[0])]
        public virtual void ValidateSaveMarketingRequestWithInvalidIDVRNInfos(string regNumberId, string regNumberVNR, string statusCode, string isSuccess, string messages, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "QuoteServices"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("RegNumberId", regNumberId);
            argumentsOfScenario.Add("RegNumberVNR", regNumberVNR);
            argumentsOfScenario.Add("StatusCode", statusCode);
            argumentsOfScenario.Add("IsSuccess", isSuccess);
            argumentsOfScenario.Add("Messages", messages);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Validate Save Marketing request with Invalid ID/VRN infos", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 8
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table336 = new TechTalk.SpecFlow.Table(new string[] {
                            "Property",
                            "Value"});
                table336.AddRow(new string[] {
                            "PrepurchaseRequestBody",
                            "SaveMarketingInvalidRegInfosCNSBike.json"});
                table336.AddRow(new string[] {
                            "QuoteRequestBody",
                            "ValidQuoteForPrepurchaseCNSBike.json"});
                table336.AddRow(new string[] {
                            "ApiVersion",
                            "V2"});
                table336.AddRow(new string[] {
                            "ContextName",
                            "CNSelectBikeContext"});
#line 9
 testRunner.Given("User has prepurchase body", ((string)(null)), table336, "Given ");
#line hidden
#line 15
 testRunner.When(string.Format("user sends request using {0} and {1}", regNumberId, regNumberVNR), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 16
 testRunner.When("User sends prepurchase requests", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 17
 testRunner.Then(string.Format("Prepurchase response returns {0} and {1} and {2}", statusCode, isSuccess, messages), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                ValidateSaveMarketingUsingInvalidIDAndVRNInfosFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                ValidateSaveMarketingUsingInvalidIDAndVRNInfosFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
