#Cover 471 cases
@CNBike
Feature: QuoteSingleFieldDataValidationCasesPart2

@QuoteServices
Scenario Outline: ValiDate quote API on each field
	Given The customer has 
	| Name         | Value1                   |
	| Url          | QuoteApi                 |
	| ApiVersion   | V1                       |
	| Context      | CNBikeContext            |
	| JsonBodyFile | ValidQuoteForCNBike.json |
	When The customer call quote API
		| Level1   | Level2   | Level3   | Level4   | Level5   | Level6   | Level7   | Value   |
		| <Level1> | <Level2> | <Level3> | <Level4> | <Level5> | <Level6> | <Level7> | <Value> |
	Then The message should be shown <StatusCode>,<IsSuccess>,"<Message>"
	Examples:	
	| Level1 | Level2  | Level3  | Level4            | Level5                  | Level6         | Level7 | Value                               | StatusCode | IsSuccess | Message                                                                |
	| Risk   | Product | Vehicle | AdditionalDrivers | Title                   |                |        | ""                                  | 400        | FALSE     | Title is required.                                                     |
	| Risk   | Product | Vehicle | AdditionalDrivers | Forenames               |                |        | missing                             | 400        | FALSE     | Forenames is required.                                                 |
	| Risk   | Product | Vehicle | AdditionalDrivers | Forenames               |                |        | null                                | 400        | FALSE     | Forenames is required.                                                 |
	| Risk   | Product | Vehicle | AdditionalDrivers | Forenames               |                |        | ""                                  | 400        | FALSE     | Forenames is required.                                                 |
	| Risk   | Product | Vehicle | AdditionalDrivers | Forenames               |                |        | Mrs abcdrertyuioghjklmbnhghyjun     | 400        | FALSE     | Forenames can not be over 30 characters.                               |
	| Risk   | Product | Vehicle | AdditionalDrivers | Surname                 |                |        | missing                             | 400        | FALSE     | Surname is required.                                                   |
	| Risk   | Product | Vehicle | AdditionalDrivers | Surname                 |                |        | null                                | 400        | FALSE     | Surname is required.                                                   |
	| Risk   | Product | Vehicle | AdditionalDrivers | Surname                 |                |        | ""                                  | 400        | FALSE     | Surname is required.                                                   |
	| Risk   | Product | Vehicle | AdditionalDrivers | Surname                 |                |        | Mrs abcdrertyuioghjklmbnhghyjun     | 400        | FALSE     | Surname can not be over 20 characters.                                 |
	| Risk   | Product | Vehicle | AdditionalDrivers | DateOfBirth             |                |        | missing                             | 400        | FALSE     | DateOfBirth is required.                                               |
	| Risk   | Product | Vehicle | AdditionalDrivers | DateOfBirth             |                |        | null                                | 400        | FALSE     | DateOfBirth is required.                                               |
	| Risk   | Product | Vehicle | AdditionalDrivers | DateOfBirth             |                |        | ""                                  | 400        | FALSE     | DateOfBirth is required.                                               |
	| Risk   | Product | Vehicle | AdditionalDrivers | UKResidentSinceDate     |                |        | missing                             | 400        | FALSE     | UKResidentSinceDate is required.                                       |
	| Risk   | Product | Vehicle | AdditionalDrivers | UKResidentSinceDate     |                |        | null                                | 400        | FALSE     | UKResidentSinceDate is required.                                       |
	| Risk   | Product | Vehicle | AdditionalDrivers | UKResidentSinceDate     |                |        | ""                                  | 400        | FALSE     | UKResidentSinceDate is required.                                       |
	| Risk   | Product | Vehicle | AdditionalDrivers | UKResidentSinceDate     |                |        | 2051-12-16T00:00:00                 | 400        | FALSE     | UKResidentSinceDate cannot be in future.                               |
	| Risk   | Product | Vehicle | AdditionalDrivers | MaritalStatus           |                |        | missing                             | 400        | FALSE     | MaritalStatus is required.                                             |
	| Risk   | Product | Vehicle | AdditionalDrivers | MaritalStatus           |                |        | null                                | 400        | FALSE     | MaritalStatus is required.                                             |
	| Risk   | Product | Vehicle | AdditionalDrivers | MaritalStatus           |                |        | ""                                  | 400        | FALSE     | MaritalStatus is required.                                             |
	| Risk   | Product | Vehicle | AdditionalDrivers | Employment              |                |        | missing                             | 400        | FALSE     | At least one Employment element is required.                           |
	| Risk   | Product | Vehicle | AdditionalDrivers | Employment              |                |        | null                                | 400        | FALSE     | At least one Employment element is required.                           |
	| Risk   | Product | Vehicle | AdditionalDrivers | Employment              |                |        | File: ProposerEmployment602.json    | 400        | FALSE     | At least one Employment element is required.                           |
	| Risk   | Product | Vehicle | AdditionalDrivers | Employment              | Type           |        | missing                             | 400        | FALSE     | Employment - Typeis required.                                          |
	| Risk   | Product | Vehicle | AdditionalDrivers | Employment              | Type           |        | null                                | 400        | FALSE     | Employment - Typeis required.                                          |
	| Risk   | Product | Vehicle | AdditionalDrivers | Employment              | Type           |        | ""                                  | 400        | FALSE     | Employment - Typeis required.                                          |
	| Risk   | Product | Vehicle | AdditionalDrivers | Employment              | Type           |        | Test                                | 400        | FALSE     | Employment - Type must be fulltime/parttime/selfemployed.              |
	| Risk   | Product | Vehicle | AdditionalDrivers | Employment              | EmploymentCode |        | missing                             | 400        | FALSE     | Employment - EmploymentCode is required.                               |
	| Risk   | Product | Vehicle | AdditionalDrivers | Employment              | EmploymentCode |        | null                                | 400        | FALSE     | Employment - EmploymentCode is required.                               |
	| Risk   | Product | Vehicle | AdditionalDrivers | Employment              | EmploymentCode |        | ""                                  | 400        | FALSE     | Employment - EmploymentCode is required.                               |
	| Risk   | Product | Vehicle | AdditionalDrivers | Employment              | OccupationCode |        | missing                             | 400        | FALSE     | Employment - OCcupationCode is required with EmploymentCode # R, U, H. |
	| Risk   | Product | Vehicle | AdditionalDrivers | Employment              | OccupationCode |        | null                                | 400        | FALSE     | Employment - OCcupationCode is required with EmploymentCode # R, U, H. |
	| Risk   | Product | Vehicle | AdditionalDrivers | Employment              | OccupationCode |        | ""                                  | 400        | FALSE     | Employment - OCcupationCode is required with EmploymentCode # R, U, H. |
	| Risk   | Product | Vehicle | AdditionalDrivers | DrivingLicence          | Type           |        | missing                             | 400        | FALSE     | Driving Licence - Type is required.                                    |
	| Risk   | Product | Vehicle | AdditionalDrivers | DrivingLicence          | Type           |        | null                                | 400        | FALSE     | Driving Licence - Type is required.                                    |
	| Risk   | Product | Vehicle | AdditionalDrivers | DrivingLicence          | Type           |        | ""                                  | 400        | FALSE     | Driving Licence - Type is required.                                    |
	| Risk   | Product | Vehicle | AdditionalDrivers | DrivingLicence          | DateObtained   |        | missing                             | 400        | FALSE     | Licence date is required.                                              |
	| Risk   | Product | Vehicle | AdditionalDrivers | DrivingLicence          | DateObtained   |        | null                                | 400        | FALSE     | Licence date is required.                                              |
	| Risk   | Product | Vehicle | AdditionalDrivers | DrivingLicence          | DateObtained   |        | ""                                  | 400        | FALSE     | Licence date is required.                                              |
	| Risk   | Product | Vehicle | AdditionalDrivers | DrivingLicence          | DateObtained   |        | 2051-12-16T00:00:00                 | 400        | FALSE     | Licence date cannot be future date.                                    |
	| Risk   | Product | Vehicle | AdditionalDrivers | PhoneNumbers            | Type           |        | missing                             | 400        | FALSE     | PhoneNumber - Type is required.                                        |
	| Risk   | Product | Vehicle | AdditionalDrivers | PhoneNumbers            | Type           |        | null                                | 400        | FALSE     | PhoneNumber - Type is required.                                        |
	| Risk   | Product | Vehicle | AdditionalDrivers | PhoneNumbers            | Type           |        | ""                                  | 400        | FALSE     | PhoneNumber - Type is required.                                        |
	| Risk   | Product | Vehicle | AdditionalDrivers | PhoneNumbers            | Number         |        | missing                             | 400        | FALSE     | PhoneNumber - Number is required.                                      |
	| Risk   | Product | Vehicle | AdditionalDrivers | PhoneNumbers            | Number         |        | null                                | 400        | FALSE     | PhoneNumber - Number is required.                                      |
	| Risk   | Product | Vehicle | AdditionalDrivers | PhoneNumbers            | Number         |        | ""                                  | 400        | FALSE     | PhoneNumber - Number is required.                                      |
	| Risk   | Product | Vehicle | AdditionalDrivers | PhoneNumbers            | Number         |        | 12345678                            | 400        | FALSE     | PhoneNumber - Number must be from 9 ~ 14 characters.                   |
	| Risk   | Product | Vehicle | AdditionalDrivers | PhoneNumbers            | Number         |        | 123456789123456                     | 400        | FALSE     | PhoneNumber - Number must be from 9 ~ 14 characters.                   |
	| Risk   | Product | Vehicle | AdditionalDrivers | Address                 | AddressLine1   |        | UK road 12UK road 12UK road 12123   | 400        | FALSE     | AddressLine1 cannot be over 32 characters.                             |
	| Risk   | Product | Vehicle | AdditionalDrivers | Address                 | AddressLine2   |        | UK road 12UK road 12UK road 12123   | 400        | FALSE     | AddressLine2 cannot be over 32 characters.                             |
	| Risk   | Product | Vehicle | AdditionalDrivers | Address                 | AddressLine3   |        | UK road 12UK road 12UK road 12123   | 400        | FALSE     | AddressLine3 cannot be over 32 characters.                             |
	| Risk   | Product | Vehicle | AdditionalDrivers | Address                 | AddressLine4   |        | UK road 12UK road 12UK road 12123   | 400        | FALSE     | AddressLine4 cannot be over 32 characters.                             |
	| Risk   | Product | Vehicle | AdditionalDrivers | Address                 | AddressLine5   |        | UK road 12UK road 12UK road 12123   | 400        | FALSE     | AddressLine5 cannot be over 32 characters.                             |
	| Risk   | Product | Vehicle | AdditionalDrivers | Address                 | PostCode       |        | EC2N 94AY                           | 400        | FALSE     | PostCode is invalid.                                                   |
	| Risk   | Product | Vehicle | AdditionalDrivers | EmailAddress            |                |        | thuongnguyenthiminh@nashtech        | 400        | FALSE     | EmailAddress is invalid.                                               |
	| Risk   | Product | Vehicle | VehicleDetail     |                         |                |        | File: VehicleVehicleDetail782.json  | 400        | FALSE     | At least one vehicle element must be added.                            |
	| Risk   | Product | Vehicle | VehicleDetail     |                         |                |        | null                                | 400        | FALSE     | At least one vehicle element must be added.                            |
	| Risk   | Product | Vehicle | VehicleDetail     |                         |                |        | missing                             | 400        | FALSE     | At least one vehicle element must be added.                            |
	| Risk   | Product | Vehicle | VehicleDetail     |                         |                |        | File: VehicleVehicleDetail787.json  | 400        | FALSE     | Vehicle elements cannot be over 4.                                     |
	| Risk   | Product | Vehicle | VehicleDetail     |                         |                |        | File: VehicleVehicleDetail1323.json | 400        | FALSE     | Cannot quote for both multi-bike and multi-rider.                      |
	| Risk   | Product | Vehicle | VehicleDetail     | VRN                     |                |        | "*Abc A                             | 400        | FALSE     | VRN is incorrect.                                                      |
	| Risk   | Product | Vehicle | VehicleDetail     | VRN                     |                |        | Q874 9FP                            | 400        | FALSE     | VRN with Q registration plate is unaCceptable.                         |
	| Risk   | Product | Vehicle | VehicleDetail     | ABICode                 |                |        | ""                                  | 400        | FALSE     | AbiCode is required.                                                   |
	| Risk   | Product | Vehicle | VehicleDetail     | ABICode                 |                |        | null                                | 400        | FALSE     | AbiCode is required.                                                   |
	| Risk   | Product | Vehicle | VehicleDetail     | ABICode                 |                |        | missing                             | 400        | FALSE     | AbiCode is required.                                                   |
	| Risk   | Product | Vehicle | VehicleDetail     | ABICode                 |                |        | 123456                              | 400        | FALSE     | AbiCode is incorrect.                                                  |
	| Risk   | Product | Vehicle | VehicleDetail     | YearOfManufacture       |                |        | ""                                  | 400        | FALSE     | YearOfManufacture is required.                                         |
	| Risk   | Product | Vehicle | VehicleDetail     | YearOfManufacture       |                |        | null                                | 400        | FALSE     | YearOfManufacture is required.                                         |
	| Risk   | Product | Vehicle | VehicleDetail     | YearOfManufacture       |                |        | missing                             | 400        | FALSE     | YearOfManufacture is required.                                         |
	| Risk   | Product | Vehicle | VehicleDetail     | YearOfManufacture       |                |        | 1928                                | 400        | FALSE     | YearOfManufacture is incorrect.                                        |
	| Risk   | Product | Vehicle | VehicleDetail     | EngineCc                |                |        | ""                                  | 400        | FALSE     | EngineCc is required.                                                  |
	| Risk   | Product | Vehicle | VehicleDetail     | EngineCc                |                |        | null                                | 400        | FALSE     | EngineCc is required.                                                  |
	| Risk   | Product | Vehicle | VehicleDetail     | EngineCc                |                |        | missing                             | 400        | FALSE     | EngineCc is required.                                                  |
	| Risk   | Product | Vehicle | VehicleDetail     | EngineCc                |                |        | -1                                  | 400        | FALSE     | EngineCc must be greater than or equal 0.                              |
	| Risk   | Product | Vehicle | VehicleDetail     | EngineCc                |                |        | 3.14                                | 400        | FALSE     | EngineCc must be greater than or equal 0.                              |
	| Risk   | Product | Vehicle | VehicleDetail     | EngineCc                |                |        | abc                                 | 400        | FALSE     | EngineCc must be greater than or equal 0.                              |
	| Risk   | Product | Vehicle | VehicleDetail     | Manufacturer            |                |        | ""                                  | 400        | FALSE     | Manufacturer is required.                                              |
	| Risk   | Product | Vehicle | VehicleDetail     | Manufacturer            |                |        | null                                | 400        | FALSE     | Manufacturer is required.                                              |
	| Risk   | Product | Vehicle | VehicleDetail     | Manufacturer            |                |        | missing                             | 400        | FALSE     | Manufacturer is required.                                              |
	| Risk   | Product | Vehicle | VehicleDetail     | Model                   |                |        | ""                                  | 400        | FALSE     | Model is required.                                                     |
	| Risk   | Product | Vehicle | VehicleDetail     | Model                   |                |        | null                                | 400        | FALSE     | Model is required.                                                     |
	| Risk   | Product | Vehicle | VehicleDetail     | Model                   |                |        | missing                             | 400        | FALSE     | Model is required.                                                     |
	| Risk   | Product | Vehicle | VehicleDetail     | DatePurchased           |                |        | ""                                  | 400        | FALSE     | DatePurchased is required.                                             |
	| Risk   | Product | Vehicle | VehicleDetail     | DatePurchased           |                |        | null                                | 400        | FALSE     | DatePurchased is required.                                             |
	| Risk   | Product | Vehicle | VehicleDetail     | DatePurchased           |                |        | missing                             | 400        | FALSE     | DatePurchased is required.                                             |
	| Risk   | Product | Vehicle | VehicleDetail     | PostCodeParkedOvernight |                |        | ""                                  | 400        | FALSE     | PostCodeParkedOvernight is required.                                   |
	| Risk   | Product | Vehicle | VehicleDetail     | PostCodeParkedOvernight |                |        | null                                | 400        | FALSE     | PostCodeParkedOvernight is required.                                   |
	| Risk   | Product | Vehicle | VehicleDetail     | PostCodeParkedOvernight |                |        | missing                             | 400        | FALSE     | PostCodeParkedOvernight is required.                                   |
	| Risk   | Product | Vehicle | VehicleDetail     | PostCodeParkedOvernight |                |        | abcdfdd                             | 400        | FALSE     | PostCodeParkedOvernight is incorrect.                                  |
	| Risk   | Product | Vehicle | VehicleDetail     | ClassOfUse              |                |        | ""                                  | 400        | FALSE     | ClassOfUse is required.                                                |
	| Risk   | Product | Vehicle | VehicleDetail     | ClassOfUse              |                |        | null                                | 400        | FALSE     | ClassOfUse is required.                                                |
	| Risk   | Product | Vehicle | VehicleDetail     | ClassOfUse              |                |        | missing                             | 400        | FALSE     | ClassOfUse is required.                                                |
	| Risk   | Product | Vehicle | VehicleDetail     | ClassOfUse              |                |        | AB                                  | 400        | FALSE     | ClassofUse is invalid.                                                 |
	| Risk   | Product | Vehicle | VehicleDetail     | Mileage                 |                |        | File: VehicleDetailMileage871.json  | 400        | FALSE     | At least one mileage element must be added.                            |