#Cover 471 cases
@CNBike
Feature: QuoteSingleFieldDataValidationHappyCases

@QuoteServices
Scenario Outline: ValiDate quote API on each field
	Given The customer has 
	| Name         | Value1                   |
	| Url          | QuoteApi                 |
	| ApiVersion   | V1                       |
	| Context      | CNBikeContext            |
	| JsonBodyFile | ValidQuoteForCNBike.json |
	When The customer call quote API
		| Level1   | Level2   | Level3   | Level4   | Level5   | Level6   | Level7   | Value   |
		| <Level1> | <Level2> | <Level3> | <Level4> | <Level5> | <Level6> | <Level7> | <Value> |
	Then The message should be shown <StatusCode>,<IsSuccess>,"<Message>"
	Examples:	
	| Level1 | Level2                | Level3           | Level4            | Level5                  | Level6       | Level7 | Value                                                                                                                                 | StatusCode | IsSuccess | Message                |
	| Risk   | Proposer              | Salutation       |                   |                         |              |        | null                                                                                                                                  | 200        | TRUE      | Get quote successfully |
	| Risk   | Proposer              | Salutation       |                   |                         |              |        | ""                                                                                                                                    | 200        | TRUE      | Get quote successfully |
	| Risk   | Proposer              | Salutation       |                   |                         |              |        | missing                                                                                                                               | 200        | TRUE      | Get quote successfully |
	| Risk   | Proposer              | Salutation       |                   |                         |              |        | Mrs Selena abcdfgtrgfdabcdfgtrgfdabcdfgtrgfdabcdfgtrgfdabcdfgtrgfdabcdfgtrgfdabcdfgtrgfdabcdfgtrgfdabcdfgtrgfdabcdfgtrgfdabcdfgtrgfdr | 200        | TRUE      | Get quote successfully |
	| Risk   | Proposer              | OtherVehicleUse  |                   |                         |              |        | missing                                                                                                                               | 200        | TRUE      | Get quote successfully |
	| Risk   | Proposer              | OtherVehicleUse  |                   |                         |              |        | null                                                                                                                                  | 200        | TRUE      | Get quote successfully |
	| Risk   | Proposer              | OtherVehicleUse  |                   |                         |              |        | ""                                                                                                                                    | 200        | TRUE      | Get quote successfully |
	| Risk   | Proposer              | Address          | AbodeType         |                         |              |        | missing                                                                                                                               | 200        | TRUE      | Get quote successfully |
	| Risk   | Proposer              | Address          | AbodeType         |                         |              |        | null                                                                                                                                  | 200        | TRUE      | Get quote successfully |
	| Risk   | Proposer              | Address          | AbodeType         |                         |              |        | ""                                                                                                                                    | 200        | TRUE      | Get quote successfully |
	| Risk   | Proposer              | Suffix           |                   |                         |              |        | Mrs Selenaz                                                                                                                           | 200        | TRUE      | Get quote successfully |
	| Risk   | Product               | Vehicle          | AdditionalDrivers | Salutation              |              |        | null                                                                                                                                  | 200        | TRUE      | Get quote successfully |
	| Risk   | Product               | Vehicle          | AdditionalDrivers | Salutation              |              |        | ""                                                                                                                                    | 200        | TRUE      | Get quote successfully |
	| Risk   | Product               | Vehicle          | AdditionalDrivers | Salutation              |              |        | missing                                                                                                                               | 200        | TRUE      | Get quote successfully |
	| Risk   | Product               | Vehicle          | AdditionalDrivers | Suffix                  |              |        | Mrs Selenaz                                                                                                                           | 200        | TRUE      | Get quote successfully |
	| Risk   | Product               | Vehicle          | AdditionalDrivers | OtherVehicleUse         |              |        | missing                                                                                                                               | 200        | TRUE      | Get quote successfully |
	| Risk   | Product               | Vehicle          | AdditionalDrivers | OtherVehicleUse         |              |        | null                                                                                                                                  | 200        | TRUE      | Get quote successfully |
	| Risk   | Product               | Vehicle          | AdditionalDrivers | OtherVehicleUse         |              |        | ""                                                                                                                                    | 200        | TRUE      | Get quote successfully |
	| Risk   | Product               | Vehicle          | VehicleDetail     | ProductionPeriod        |              |        | ""                                                                                                                                    | 200        | TRUE      | Get quote successfully |
	| Risk   | Product               | Vehicle          | VehicleDetail     | ProductionPeriod        |              |        | null                                                                                                                                  | 200        | TRUE      | Get quote successfully |
	| Risk   | Product               | Vehicle          | VehicleDetail     | ProductionPeriod        |              |        | missing                                                                                                                               | 200        | TRUE      | Get quote successfully |
	| Risk   | Product               | Vehicle          | VehicleDetail     | BodyStyle               |              |        | ""                                                                                                                                    | 200        | TRUE      | Get quote successfully |
	| Risk   | Product               | Vehicle          | VehicleDetail     | BodyStyle               |              |        | null                                                                                                                                  | 200        | TRUE      | Get quote successfully |
	| Risk   | Product               | Vehicle          | VehicleDetail     | BodyStyle               |              |        | missing                                                                                                                               | 200        | TRUE      | Get quote successfully |
	| Risk   | Product               | Vehicle          | VehicleDetail     | Seats                   |              |        | ""                                                                                                                                    | 200        | TRUE      | Get quote successfully |
	| Risk   | Product               | Vehicle          | VehicleDetail     | Seats                   |              |        | null                                                                                                                                  | 200        | TRUE      | Get quote successfully |
	| Risk   | Product               | Vehicle          | VehicleDetail     | Seats                   |              |        | missing                                                                                                                               | 200        | TRUE      | Get quote successfully |
	| Risk   | Product               | Vehicle          | VehicleDetail     | HandednessDrivingType   |              |        | ""                                                                                                                                    | 200        | TRUE      | Get quote successfully |
	| Risk   | Product               | Vehicle          | VehicleDetail     | HandednessDrivingType   |              |        | null                                                                                                                                  | 200        | TRUE      | Get quote successfully |
	| Risk   | Product               | Vehicle          | VehicleDetail     | HandednessDrivingType   |              |        | missing                                                                                                                               | 200        | TRUE      | Get quote successfully |
	| Risk   | Product               | Vehicle          | VehicleDetail     | Abs                     |              |        | ""                                                                                                                                    | 200        | TRUE      | Get quote successfully |
	| Risk   | Product               | Vehicle          | VehicleDetail     | Abs                     |              |        | null                                                                                                                                  | 200        | TRUE      | Get quote successfully |
	| Risk   | Product               | Vehicle          | VehicleDetail     | Abs                     |              |        | missing                                                                                                                               | 200        | TRUE      | Get quote successfully |
	| Risk   | Product               | Vehicle          | VehicleDetail     | Owner                   |              |        | null                                                                                                                                  | 200        | TRUE      | Get quote successfully |
	| Risk   | Product               | Vehicle          | VehicleDetail     | Owner                   |              |        | missing                                                                                                                               | 200        | TRUE      | Get quote successfully |
	| Risk   | Product               | Vehicle          | VehicleDetail     | Owner                   |              |        | ""                                                                                                                                    | 200        | TRUE      | Get quote successfully |
	| Risk   | Product               | Vehicle          | VehicleDetail     | RegisteredKeeper        |              |        | ""                                                                                                                                    | 204        | FALSE     | NoContent              |
	| Risk   | Product               | Vehicle          | VehicleDetail     | RegisteredKeeper        |              |        | null                                                                                                                                  | 204        | FALSE     | NoContent              |
	| Risk   | Product               | Vehicle          | VehicleDetail     | RegisteredKeeper        |              |        | missing                                                                                                                               | 204        | FALSE     | NoContent              |
	| Risk   | Product               | Vehicle          | VehicleDetail     | LocationParkedOvernight |              |        | ""                                                                                                                                    | 200        | TRUE      | Get quote successfully |
	| Risk   | Product               | Vehicle          | VehicleDetail     | LocationParkedOvernight |              |        | null                                                                                                                                  | 200        | TRUE      | Get quote successfully |
	| Risk   | Product               | Vehicle          | VehicleDetail     | LocationParkedOvernight |              |        | missing                                                                                                                               | 200        | TRUE      | Get quote successfully |
	| Risk   | MaxNumOfQuotes        |                  |                   |                         |              |        | -1                                                                                                                                    | 200        | TRUE      | Get quote successfully |
	| Risk   | MaxNumOfQuotes        |                  |                   |                         |              |        | 3.14                                                                                                                                  | 200        | TRUE      | Get quote successfully |
	| Risk   | MaxNumOfQuotes        |                  |                   |                         |              |        | abc                                                                                                                                   | 200        | TRUE      | Get quote successfully |
	| Risk   | MaxNumOfQuotesToStore |                  |                   |                         |              |        | -1                                                                                                                                    | 200        | TRUE      | Get quote successfully |
	| Risk   | MaxNumOfQuotesToStore |                  |                   |                         |              |        | 3.14                                                                                                                                  | 200        | TRUE      | Get quote successfully |
	| Risk   | MaxNumOfQuotesToStore |                  |                   |                         |              |        | abc                                                                                                                                   | 200        | TRUE      | Get quote successfully |
	| Risk   | Product               | Claims           | PersonId          |                         |              |        | 15                                                                                                                                    | 200        | TRUE      | Get quote successfully |
	| Risk   | Product               | Convictions      | PersonId          |                         |              |        | 15                                                                                                                                    | 200        | TRUE      | Get quote successfully |
	| Risk   | OptionalExtras        | Amount           |                   |                         |              |        | -1                                                                                                                                    | 200        | TRUE      | Get quote successfully |
	| Risk   | OptionalExtras        | CommissionAmount |                   |                         |              |        | -1                                                                                                                                    | 200        | TRUE      | Get quote successfully |
	| Risk   | Product               | Vehicle          | AdditionalDrivers | Salutation              |              |        | Mrs Selena abcdfgtrgfdabcdfgtrgfdabcdfgtrgfdabcdfgtrgfdabcdfgtrgfdabcdfgtrgfdabcdfgtrgfdabcdfgtrgfdabcdfgtrgfdabcdfgtrgfdabcdfgtrgfdr | 200        | TRUE      | Get quote successfully |

