// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AtlantaApi.Feature.CNBike.QuoteService.SaveMarketing.V1
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "CNBike")]
    public partial class ValidateSaveMarketingDuplicateFieldFeature : object, Xunit.IClassFixture<ValidateSaveMarketingDuplicateFieldFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = new string[] {
                "CNBike"};
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "SaveMarketingDuplicateField.feature"
#line hidden
        
        public ValidateSaveMarketingDuplicateFieldFeature(ValidateSaveMarketingDuplicateFieldFeature.FixtureData fixtureData, AtlantaApi_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Feature/CNBike/QuoteService/SaveMarketing/V1", "Validate Save Marketing Duplicate Field", null, ProgrammingLanguage.CSharp, new string[] {
                        "CNBike"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Validate Save Marketing request with single fields")]
        [Xunit.TraitAttribute("FeatureTitle", "Validate Save Marketing Duplicate Field")]
        [Xunit.TraitAttribute("Description", "Validate Save Marketing request with single fields")]
        [Xunit.TraitAttribute("Category", "QuoteServices")]
        [Xunit.InlineDataAttribute("RegNumber", "Id", "File: SaveMarketingDuplicateId.json", "400", "false", "RegNumbers - Id has duplicate items.", new string[0])]
        [Xunit.InlineDataAttribute("RegNumber", "VRN", "File: SaveMarketingDuplicateVRN.json", "400", "false", "RegNumbers - Vrn has duplicate items.", new string[0])]
        public virtual void ValidateSaveMarketingRequestWithSingleFields(string level1, string level2, string value, string statusCode, string isSuccess, string messages, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "QuoteServices"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Level1", level1);
            argumentsOfScenario.Add("Level2", level2);
            argumentsOfScenario.Add("Value", value);
            argumentsOfScenario.Add("StatusCode", statusCode);
            argumentsOfScenario.Add("IsSuccess", isSuccess);
            argumentsOfScenario.Add("Messages", messages);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Validate Save Marketing request with single fields", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table242 = new TechTalk.SpecFlow.Table(new string[] {
                            "Property",
                            "Value"});
                table242.AddRow(new string[] {
                            "SaveMarketingRequestBody",
                            "SaveMarketingRequestBodyCNBike.json"});
                table242.AddRow(new string[] {
                            "QuoteRequestBody",
                            "ValidQuoteForPrepurchaseCNBike.json"});
                table242.AddRow(new string[] {
                            "ApiVersion",
                            "V1"});
                table242.AddRow(new string[] {
                            "ContextName",
                            "CNBikeContext"});
#line 7
 testRunner.Given("User has Save Marketing body", ((string)(null)), table242, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table243 = new TechTalk.SpecFlow.Table(new string[] {
                            "Level1",
                            "Level2",
                            "Value"});
                table243.AddRow(new string[] {
                            string.Format("{0}", level1),
                            string.Format("{0}", level2),
                            string.Format("{0}", value)});
#line 13
 testRunner.When("User send Save Marketing request", ((string)(null)), table243, "When ");
#line hidden
#line 16
 testRunner.Then(string.Format("Save Marketing response returns {0} and {1} and {2}", statusCode, isSuccess, messages), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                ValidateSaveMarketingDuplicateFieldFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                ValidateSaveMarketingDuplicateFieldFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
