// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.6.0.0
//      SpecFlow Generator Version:3.6.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AtlantaApi.Feature.CNSelectedBike.QuoteService.Recall.V2
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.6.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class RecallAQuoteWhenWebReferenceIsValidPostcodeDateOfBirthAreValidAndMatchedTheQuoteOfRequestedWebReferenceFeature : object, Xunit.IClassFixture<RecallAQuoteWhenWebReferenceIsValidPostcodeDateOfBirthAreValidAndMatchedTheQuoteOfRequestedWebReferenceFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "RecallRequestValidParameter.feature"
#line hidden
        
        public RecallAQuoteWhenWebReferenceIsValidPostcodeDateOfBirthAreValidAndMatchedTheQuoteOfRequestedWebReferenceFeature(RecallAQuoteWhenWebReferenceIsValidPostcodeDateOfBirthAreValidAndMatchedTheQuoteOfRequestedWebReferenceFeature.FixtureData fixtureData, AtlantaApi_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Feature/CNSelectedBike/QuoteService/Recall/V2", "Recall a quote when webReference is valid, Postcode & DateOfBirth are valid and m" +
                    "atched the quote of requested webReference", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Recall a quote when webReference is valid, Postcode & DateOfBirth are valid and m" +
            "atched the quote of requested webReference")]
        [Xunit.TraitAttribute("FeatureTitle", "Recall a quote when webReference is valid, Postcode & DateOfBirth are valid and m" +
            "atched the quote of requested webReference")]
        [Xunit.TraitAttribute("Description", "Recall a quote when webReference is valid, Postcode & DateOfBirth are valid and m" +
            "atched the quote of requested webReference")]
        [Xunit.TraitAttribute("Category", "QuoteServices")]
        [Xunit.InlineDataAttribute("200", "Get quote successfully", new string[0])]
        public virtual void RecallAQuoteWhenWebReferenceIsValidPostcodeDateOfBirthAreValidAndMatchedTheQuoteOfRequestedWebReference(string statusCode, string messages, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "QuoteServices"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("StatusCode", statusCode);
            argumentsOfScenario.Add("Messages", messages);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Recall a quote when webReference is valid, Postcode & DateOfBirth are valid and m" +
                    "atched the quote of requested webReference", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 9
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table215 = new TechTalk.SpecFlow.Table(new string[] {
                            "Property",
                            "Value"});
                table215.AddRow(new string[] {
                            "QuoteRequestBody",
                            "ValidQuoteForRecall.json"});
                table215.AddRow(new string[] {
                            "RecallRequestBody",
                            "RecallBody.json"});
                table215.AddRow(new string[] {
                            "ApiVersion",
                            "V2"});
                table215.AddRow(new string[] {
                            "ContextName",
                            "CNSelectBikeContext"});
#line 10
 testRunner.Given("User has recall body", ((string)(null)), table215, "Given ");
#line hidden
#line 16
 testRunner.When("User send recall service", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 17
 testRunner.Then(string.Format("Recall response returns {0} and {1}", statusCode, messages), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.6.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                RecallAQuoteWhenWebReferenceIsValidPostcodeDateOfBirthAreValidAndMatchedTheQuoteOfRequestedWebReferenceFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                RecallAQuoteWhenWebReferenceIsValidPostcodeDateOfBirthAreValidAndMatchedTheQuoteOfRequestedWebReferenceFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
