// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AtlantaApi.Feature.CNBike.QuoteService.PartialQuote.V1
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "CNBike")]
    public partial class PartialQuoteSingleFieldDataValidationCasesPart4Feature : object, Xunit.IClassFixture<PartialQuoteSingleFieldDataValidationCasesPart4Feature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = new string[] {
                "CNBike"};
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "PartialQuoteSingleFieldDataValidationPart4.feature"
#line hidden
        
        public PartialQuoteSingleFieldDataValidationCasesPart4Feature(PartialQuoteSingleFieldDataValidationCasesPart4Feature.FixtureData fixtureData, AtlantaApi_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Feature/CNBike/QuoteService/PartialQuote/V1", "PartialQuoteSingleFieldDataValidationCasesPart4", null, ProgrammingLanguage.CSharp, new string[] {
                        "CNBike"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="ValiDate Partial quote API on each field")]
        [Xunit.TraitAttribute("FeatureTitle", "PartialQuoteSingleFieldDataValidationCasesPart4")]
        [Xunit.TraitAttribute("Description", "ValiDate Partial quote API on each field")]
        [Xunit.TraitAttribute("Category", "QuoteServices")]
        [Xunit.InlineDataAttribute("Risk", "Product", "Vehicle", "AdditionalDrivers", "Employment", "EmployerCode", "", "missing", "400", "FALSE", "Employment - EmployerCode is required with EmploymentCode # R, U, H, FTE.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Vehicle", "AdditionalDrivers", "Employment", "EmployerCode", "", "null", "400", "FALSE", "Employment - EmployerCode is required with EmploymentCode # R, U, H, FTE.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Product", "Vehicle", "AdditionalDrivers", "Employment", "EmployerCode", "", "\"\"", "400", "FALSE", "Employment - EmployerCode is required with EmploymentCode # R, U, H, FTE.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Proposer", "Employment", "EmployerCode", "", "", "", "missing", "400", "FALSE", "Employment - EmployerCode is required with EmploymentCode # R, U, H, FTE.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Proposer", "Employment", "EmployerCode", "", "", "", "null", "400", "FALSE", "Employment - EmployerCode is required with EmploymentCode # R, U, H, FTE.", new string[0])]
        [Xunit.InlineDataAttribute("Risk", "Proposer", "Employment", "EmployerCode", "", "", "", "\"\"", "400", "FALSE", "Employment - EmployerCode is required with EmploymentCode # R, U, H, FTE.", new string[0])]
        public virtual void ValiDatePartialQuoteAPIOnEachField(string level1, string level2, string level3, string level4, string level5, string level6, string level7, string value, string statusCode, string isSuccess, string message, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "QuoteServices"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Level1", level1);
            argumentsOfScenario.Add("Level2", level2);
            argumentsOfScenario.Add("Level3", level3);
            argumentsOfScenario.Add("Level4", level4);
            argumentsOfScenario.Add("Level5", level5);
            argumentsOfScenario.Add("Level6", level6);
            argumentsOfScenario.Add("Level7", level7);
            argumentsOfScenario.Add("Value", value);
            argumentsOfScenario.Add("StatusCode", statusCode);
            argumentsOfScenario.Add("IsSuccess", isSuccess);
            argumentsOfScenario.Add("Message", message);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ValiDate Partial quote API on each field", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table218 = new TechTalk.SpecFlow.Table(new string[] {
                            "Name",
                            "Value1"});
                table218.AddRow(new string[] {
                            "Url",
                            "PartialQuote"});
                table218.AddRow(new string[] {
                            "ApiVersion",
                            "V1"});
                table218.AddRow(new string[] {
                            "Context",
                            "CNBikeContext"});
                table218.AddRow(new string[] {
                            "JsonBodyFile",
                            "ValidPartialQuoteForCNBike.json"});
#line 7
 testRunner.Given("The customer has", ((string)(null)), table218, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table219 = new TechTalk.SpecFlow.Table(new string[] {
                            "Level1",
                            "Level2",
                            "Level3",
                            "Level4",
                            "Level5",
                            "Level6",
                            "Level7",
                            "Value"});
                table219.AddRow(new string[] {
                            string.Format("{0}", level1),
                            string.Format("{0}", level2),
                            string.Format("{0}", level3),
                            string.Format("{0}", level4),
                            string.Format("{0}", level5),
                            string.Format("{0}", level6),
                            string.Format("{0}", level7),
                            string.Format("{0}", value)});
#line 13
 testRunner.When("The customer call quote API", ((string)(null)), table219, "When ");
#line hidden
#line 16
 testRunner.Then(string.Format("The message should be shown {0},{1},\"{2}\"", statusCode, isSuccess, message), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                PartialQuoteSingleFieldDataValidationCasesPart4Feature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                PartialQuoteSingleFieldDataValidationCasesPart4Feature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
