// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AtlantaApi.Feature.BeWiser.WebHookService.V2
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "BeWiser")]
    public partial class PaymentOutcomeValidationMissingStartMonthAndStartYearFeature : object, Xunit.IClassFixture<PaymentOutcomeValidationMissingStartMonthAndStartYearFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = new string[] {
                "BeWiser"};
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "PaymentOutcomeMissingStartYear.feature"
#line hidden
        
        public PaymentOutcomeValidationMissingStartMonthAndStartYearFeature(PaymentOutcomeValidationMissingStartMonthAndStartYearFeature.FixtureData fixtureData, AtlantaApi_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Feature/BeWiser/WebHookService/V2", "PaymentOutcomeValidationMissingStartMonthAndStartYear", null, ProgrammingLanguage.CSharp, new string[] {
                        "BeWiser"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="PaymentOutcomeValidation")]
        [Xunit.TraitAttribute("FeatureTitle", "PaymentOutcomeValidationMissingStartMonthAndStartYear")]
        [Xunit.TraitAttribute("Description", "PaymentOutcomeValidation")]
        [Xunit.TraitAttribute("Category", "WebhookServices")]
        [Xunit.InlineDataAttribute("StartYear", "missing", "200", "pc/confirmation?", new string[0])]
        public virtual void PaymentOutcomeValidation(string level1, string value, string statusCode, string messages, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "WebhookServices"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Level1", level1);
            argumentsOfScenario.Add("Value", value);
            argumentsOfScenario.Add("StatusCode", statusCode);
            argumentsOfScenario.Add("Messages", messages);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PaymentOutcomeValidation", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 9
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table187 = new TechTalk.SpecFlow.Table(new string[] {
                            "Property",
                            "Value"});
                table187.AddRow(new string[] {
                            "Uri",
                            "/api/V2/payment/outcome/A|AN|Bewiser%20Car|PC|SCAR"});
                table187.AddRow(new string[] {
                            "WebHookBody",
                            "WebHookBodyMissingStartMonthBeWiser.json"});
                table187.AddRow(new string[] {
                            "QuoteRequestBody",
                            "ValidQuoteBeWiserSuccess.json"});
                table187.AddRow(new string[] {
                            "PaymentRequestBody",
                            "RegisterPaymentRequestBodyBeWiser.json"});
                table187.AddRow(new string[] {
                            "SaveMarketingRequestBody",
                            "SaveMarketingRequestBodyBeWiser.json"});
                table187.AddRow(new string[] {
                            "SaveDebitRequestBody",
                            "SaveDebitRequestBodyBeWiser.json"});
                table187.AddRow(new string[] {
                            "SavePaymentInfoRequestBody",
                            "SavePaymentInfoRequestBodyBeWiser.json"});
                table187.AddRow(new string[] {
                            "ApiVersion",
                            "V3"});
                table187.AddRow(new string[] {
                            "ContextName",
                            "BeWiser"});
#line 10
 testRunner.Given("I have wrapUp table", ((string)(null)), table187, "Given ");
#line hidden
#line 22
 testRunner.When("User send a Register PayInFull Payment service", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table188 = new TechTalk.SpecFlow.Table(new string[] {
                            "Level1",
                            "Value"});
                table188.AddRow(new string[] {
                            string.Format("{0}", level1),
                            string.Format("{0}", value)});
#line 23
 testRunner.And("User send a WebHook service with", ((string)(null)), table188, "And ");
#line hidden
#line 26
 testRunner.Then(string.Format("Payment response returns {0} and {1}", statusCode, messages), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                PaymentOutcomeValidationMissingStartMonthAndStartYearFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                PaymentOutcomeValidationMissingStartMonthAndStartYearFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
