#Cover 471 cases
@SafeGuardMH
Feature: QuoteSingleFieldDataValidationCasesPart2

@QuoteServices
Scenario Outline: ValiDate quote API on each field
	Given The customer has 
	| Name         | Value1                             |
	| Url          | QuoteApi                           |
	| ApiVersion   | V2                                 |
	| Context      | SafeGuardMH                        |
	| JsonBodyFile | ValidQuoteForSGGetQuote.json |
	When The customer call quote API
		| Level1   | Level2   | Level3   | Level4   | Level5   | Level6   | Level7   | Value   |
		| <Level1> | <Level2> | <Level3> | <Level4> | <Level5> | <Level6> | <Level7> | <Value> |
	Then The message should be shown <StatusCode>,<IsSuccess>,"<Message>"
	Examples:	
	| Level1 | Level2  | Level3  | Level4            | Level5              | Level6         | Level7 | Value                                                                                                                                 | StatusCode | IsSuccess | Message                                                                                    |
	| Risk   | Product | Vehicle | AdditionalDrivers |                     |                |        | File: VehicleAdditionalDrives684ScenicMH.json                                                                                         | 400        | FALSE     | Additional rider's ID must be 2, 3, 4 or 5. number of additional drivers cannot be over 4. |
	| Risk   | Product | Vehicle | AdditionalDrivers | Id                  |                |        | ""                                                                                                                                    | 400        | FALSE     | Additional rider's ID is required.                                                         |
	| Risk   | Product | Vehicle | AdditionalDrivers | Id                  |                |        | null                                                                                                                                  | 400        | FALSE     | Additional rider's ID is required.                                                         |
	| Risk   | Product | Vehicle | AdditionalDrivers | Id                  |                |        | missing                                                                                                                               | 400        | FALSE     | Additional rider's ID is required.                                                         |
	| Risk   | Product | Vehicle | AdditionalDrivers | Id                  |                |        | 1                                                                                                                                     | 400        | FALSE     | Additional rider's ID must be 2, 3, 4 or 5.                                                |
	| Risk   | Product | Vehicle | AdditionalDrivers | Id                  |                |        | 6                                                                                                                                     | 400        | FALSE     | Additional rider's ID must be 2, 3, 4 or 5.                                                |
	| Risk   | Product | Vehicle | AdditionalDrivers |                     |                |        | File: VehicleAdditionalDrives690ScenicMH.json                                                                                         | 400        | FALSE     | Additional rider's ID must be unique.                                                      |
	| Risk   | Product | Vehicle | AdditionalDrivers | Salutation          |                |        | null                                                                                                                                  | 400        | FALSE     | Salutation is required.                                                                    |
	| Risk   | Product | Vehicle | AdditionalDrivers | Salutation          |                |        | ""                                                                                                                                    | 400        | FALSE     | Salutation is required.                                                                    |
	| Risk   | Product | Vehicle | AdditionalDrivers | Salutation          |                |        | missing                                                                                                                               | 400        | FALSE     | Salutation is required.                                                                    |
	| Risk   | Product | Vehicle | AdditionalDrivers | Salutation          |                |        | Mrs Selena abcdfgtrgfdabcdfgtrgfdabcdfgtrgfdabcdfgtrgfdabcdfgtrgfdabcdfgtrgfdabcdfgtrgfdabcdfgtrgfdabcdfgtrgfdabcdfgtrgfdabcdfgtrgfdr | 400        | FALSE     | Salutation cannot be over 121 characters.                                                  |
	| Risk   | Product | Vehicle | AdditionalDrivers | Title               |                |        | missing                                                                                                                               | 400        | FALSE     | Title is required.                                                                         |
	| Risk   | Product | Vehicle | AdditionalDrivers | Title               |                |        | null                                                                                                                                  | 400        | FALSE     | Title is required.                                                                         |
	| Risk   | Product | Vehicle | AdditionalDrivers | Title               |                |        | ""                                                                                                                                    | 400        | FALSE     | Title is required.                                                                         |
	| Risk   | Product | Vehicle | AdditionalDrivers | Forenames           |                |        | missing                                                                                                                               | 400        | FALSE     | Forenames is required.                                                                     |
	| Risk   | Product | Vehicle | AdditionalDrivers | Forenames           |                |        | null                                                                                                                                  | 400        | FALSE     | Forenames is required.                                                                     |
	| Risk   | Product | Vehicle | AdditionalDrivers | Forenames           |                |        | ""                                                                                                                                    | 400        | FALSE     | Forenames is required.                                                                     |
	| Risk   | Product | Vehicle | AdditionalDrivers | Forenames           |                |        | Mrs abcdrertyuioghjklmbnhghyjun                                                                                                       | 400        | FALSE     | Forenames can not be over 30 characters.                                                   |
	| Risk   | Product | Vehicle | AdditionalDrivers | Surname             |                |        | missing                                                                                                                               | 400        | FALSE     | Surname is required.                                                                       |
	| Risk   | Product | Vehicle | AdditionalDrivers | Surname             |                |        | null                                                                                                                                  | 400        | FALSE     | Surname is required.                                                                       |
	| Risk   | Product | Vehicle | AdditionalDrivers | Surname             |                |        | ""                                                                                                                                    | 400        | FALSE     | Surname is required.                                                                       |
	| Risk   | Product | Vehicle | AdditionalDrivers | Surname             |                |        | Mrs qwertyMrs qwertyMrs qwertyMrs qwertyMrs qwertyMrs qwertyMrs qwertyMrs qwertyMrs qwertyMrs qwertyv                                 | 400        | FALSE     | Surname cannot be over 100 characters.                                                     |
	| Risk   | Product | Vehicle | AdditionalDrivers | Suffix              |                |        | Mrs Selenaz                                                                                                                           | 400        | FALSE     | suffix can not be over 10 characters.                                                      |
	| Risk   | Product | Vehicle | AdditionalDrivers | DateOfBirth         |                |        | missing                                                                                                                               | 400        | FALSE     | DateOfBirth is required.                                                                   |
	| Risk   | Product | Vehicle | AdditionalDrivers | UKResidentSinceDate |                |        | missing                                                                                                                               | 400        | FALSE     | UKResidentSinceDate is required.                                                           |
	| Risk   | Product | Vehicle | AdditionalDrivers | UKResidentSinceDate |                |        | 2021-12-16T00:00:00                                                                                                                   | 400        | FALSE     | UKResidentSinceDate cannot be in future.                                                   |
	| Risk   | Product | Vehicle | AdditionalDrivers | MaritalStatus       |                |        | missing                                                                                                                               | 400        | FALSE     | MaritalStatus is required.                                                                 |
	| Risk   | Product | Vehicle | AdditionalDrivers | MaritalStatus       |                |        | null                                                                                                                                  | 400        | FALSE     | MaritalStatus is required.                                                                 |
	| Risk   | Product | Vehicle | AdditionalDrivers | MaritalStatus       |                |        | ""                                                                                                                                    | 400        | FALSE     | MaritalStatus is required.                                                                 |
	| Risk   | Product | Vehicle | AdditionalDrivers | Employment          |                |        | missing                                                                                                                               | 400        | FALSE     | fulltime & parttime occupation are required.                                               |
	| Risk   | Product | Vehicle | AdditionalDrivers | Employment          |                |        | null                                                                                                                                  | 400        | FALSE     | fulltime & parttime occupation are required.                                               |
	| Risk   | Product | Vehicle | AdditionalDrivers | Employment          |                |        | File: ProposerEmployment602.json                                                                                                      | 400        | FALSE     | fulltime & parttime occupation are required.                                               |
	| Risk   | Product | Vehicle | AdditionalDrivers | Employment          | Type           |        | missing                                                                                                                               | 400        | FALSE     | Employment - Typeis required.                                                              |
	| Risk   | Product | Vehicle | AdditionalDrivers | Employment          | Type           |        | null                                                                                                                                  | 400        | FALSE     | Employment - Typeis required.                                                              |
	| Risk   | Product | Vehicle | AdditionalDrivers | Employment          | Type           |        | ""                                                                                                                                    | 400        | FALSE     | Employment - Typeis required.                                                              |
	| Risk   | Product | Vehicle | AdditionalDrivers | Employment          | Type           |        | Test                                                                                                                                  | 400        | FALSE     | Employment - Type must be fulltime/parttime.                                               |
	| Risk   | Product | Vehicle | AdditionalDrivers | Employment          | EmploymentCode |        | missing                                                                                                                               | 400        | FALSE     | Employment - EmploymentCode is required.                                                   |
	| Risk   | Product | Vehicle | AdditionalDrivers | Employment          | EmploymentCode |        | null                                                                                                                                  | 400        | FALSE     | Employment - EmploymentCode is required.                                                   |
	| Risk   | Product | Vehicle | AdditionalDrivers | Employment          | EmploymentCode |        | ""                                                                                                                                    | 400        | FALSE     | Employment - EmploymentCode is required.                                                   |
	| Risk   | Product | Vehicle | AdditionalDrivers | Employment          | OccupationCode |        | missing                                                                                                                               | 400        | FALSE     | Employment - OCcupationCode is required.                                                   |
	| Risk   | Product | Vehicle | AdditionalDrivers | Employment          | OccupationCode |        | null                                                                                                                                  | 400        | FALSE     | Employment - OCcupationCode is required.                                                   |
	| Risk   | Product | Vehicle | AdditionalDrivers | Employment          | OccupationCode |        | ""                                                                                                                                    | 400        | FALSE     | Employment - OCcupationCode is required.                                                   |
	| Risk   | Product | Vehicle | AdditionalDrivers | Employment          | EmployerCode   |        | missing                                                                                                                               | 400        | FALSE     | Employment - EmployerCode is required.                                                     |
	| Risk   | Product | Vehicle | AdditionalDrivers | Employment          | EmployerCode   |        | null                                                                                                                                  | 400        | FALSE     | Employment - EmployerCode is required.                                                     |
	| Risk   | Product | Vehicle | AdditionalDrivers | Employment          | EmployerCode   |        | ""                                                                                                                                    | 400        | FALSE     | Employment - EmployerCode is required.                                                     |
	| Risk   | Product | Vehicle | AdditionalDrivers | DrivingLicence      | Type           |        | missing                                                                                                                               | 400        | FALSE     | Driving Licence - Type is required.                                                        |
	| Risk   | Product | Vehicle | AdditionalDrivers | DrivingLicence      | Type           |        | null                                                                                                                                  | 400        | FALSE     | Driving Licence - Type is required.                                                        |
	| Risk   | Product | Vehicle | AdditionalDrivers | DrivingLicence      | Type           |        | ""                                                                                                                                    | 400        | FALSE     | Driving Licence - Type is required.                                                        |
	| Risk   | Product | Vehicle | AdditionalDrivers | DrivingLicence      | DateObtained   |        | missing                                                                                                                               | 400        | FALSE     | Licence date is required.                                                                  |
	| Risk   | Product | Vehicle | AdditionalDrivers | DrivingLicence      | DateObtained   |        | 2021-12-16T00:00:00                                                                                                                   | 400        | FALSE     | Licence date cannot be future date.                                                        |
	| Risk   | Product | Vehicle | AdditionalDrivers | OtherVehicleUse     |                |        | missing                                                                                                                               | 400        | FALSE     | OtherVehicleUse is required.                                                               |
	| Risk   | Product | Vehicle | AdditionalDrivers | OtherVehicleUse     |                |        | null                                                                                                                                  | 400        | FALSE     | OtherVehicleUse is required.                                                               |
	| Risk   | Product | Vehicle | AdditionalDrivers | OtherVehicleUse     |                |        | ""                                                                                                                                    | 400        | FALSE     | OtherVehicleUse is required.                                                               |
	| Risk   | Product | Vehicle | AdditionalDrivers | EmailAddress        |                |        | thuongnguyenthiminh@nashtech                                                                                                          | 400        | FALSE     | EmailAddress is invalid.                                                                   |
	| Risk   | Product | Vehicle | VehicleDetail     |                     |                |        | File: VehicleVehicleDetail782.json                                                                                                    | 400        | FALSE     | At least one vehicle element must be added.                                                |
	| Risk   | Product | Vehicle | VehicleDetail     |                     |                |        | null                                                                                                                                  | 400        | FALSE     | At least one vehicle element must be added.                                                |
	| Risk   | Product | Vehicle | VehicleDetail     |                     |                |        | missing                                                                                                                               | 400        | FALSE     | At least one vehicle element must be added.                                                |
	| Risk   | Product | Vehicle | VehicleDetail     |                     |                |        | File: VehicleVehicleDetail787ScenicMH.json                                                                                            | 400        | FALSE     | Vehicle elements cannot be over 1.                                                         |
	| Risk   | Product | Vehicle | VehicleDetail     | VRN                 |                |        | "*Abc A                                                                                                                               | 400        | FALSE     | VRN is incorrect.                                                                          |
	| Risk   | Product | Vehicle | VehicleDetail     | VRN                 |                |        | Q874 9FP                                                                                                                              | 400        | FALSE     | VRN with Q registration plate is unaCceptable.                                             |
	| Risk   | Product | Vehicle | VehicleDetail     | YearOfManufacture   |                |        | ""                                                                                                                                    | 400        | FALSE     | YearOfManufacture is required.                                                             |
	| Risk   | Product | Vehicle | VehicleDetail     | YearOfManufacture   |                |        | null                                                                                                                                  | 400        | FALSE     | YearOfManufacture is required.                                                             |
	| Risk   | Product | Vehicle | VehicleDetail     | YearOfManufacture   |                |        | missing                                                                                                                               | 400        | FALSE     | YearOfManufacture is required.                                                             |
	| Risk   | Product | Vehicle | VehicleDetail     | EngineCc            |                |        | ""                                                                                                                                    | 400        | FALSE     | EngineCc is required.                                                                      |
	| Risk   | Product | Vehicle | VehicleDetail     | EngineCc            |                |        | null                                                                                                                                  | 400        | FALSE     | EngineCc is required.                                                                      |
	| Risk   | Product | Vehicle | VehicleDetail     | EngineCc            |                |        | missing                                                                                                                               | 400        | FALSE     | EngineCc is required.                                                                      |
	| Risk   | Product | Vehicle | VehicleDetail     | EngineCc            |                |        | -1                                                                                                                                    | 400        | FALSE     | EngineCc must be integer greater than or equal 0.                                          |
	| Risk   | Product | Vehicle | VehicleDetail     | EngineCc            |                |        | 3.14                                                                                                                                  | 400        | FALSE     | EngineCc must be integer greater than or equal 0.                                          |
	| Risk   | Product | Vehicle | VehicleDetail     | EngineCc            |                |        | abc                                                                                                                                   | 400        | FALSE     | EngineCc must be integer greater than or equal 0.                                          |
	| Risk   | Product | Vehicle | VehicleDetail     | Manufacturer        |                |        | ""                                                                                                                                    | 400        | FALSE     | Manufacturer is required.                                                                  |
	| Risk   | Product | Vehicle | VehicleDetail     | Manufacturer        |                |        | null                                                                                                                                  | 400        | FALSE     | Manufacturer is required.                                                                  |
	| Risk   | Product | Vehicle | VehicleDetail     | Manufacturer        |                |        | missing                                                                                                                               | 400        | FALSE     | Manufacturer is required.                                                                  |
	| Risk   | Product | Vehicle | VehicleDetail     | Model               |                |        | ""                                                                                                                                    | 400        | FALSE     | Model is required.                                                                         |
	| Risk   | Product | Vehicle | VehicleDetail     | Model               |                |        | null                                                                                                                                  | 400        | FALSE     | Model is required.                                                                         |
	| Risk   | Product | Vehicle | VehicleDetail     | Model               |                |        | missing                                                                                                                               | 400        | FALSE     | Model is required.                                                                         |