#Cover 471 cases
@CNSBike
Feature: QuoteSingleFieldDataValidationCasesPart1

@QuoteServices
Scenario Outline: ValiDate quote API on each field
	Given The customer has 
	| Name         | Value1              |
	| Url          | QuoteApi            |
	| ApiVersion   | V2                  |
	| Context      | CNSelectBikeContext |
	| JsonBodyFile | ValidQuoteCNSBike.json     |
	When The customer call quote API
		| Level1   | Level2   | Level3   | Level4   | Level5   | Level6   | Level7   | Value   |
		| <Level1> | <Level2> | <Level3> | <Level4> | <Level5> | <Level6> | <Level7> | <Value> |
	Then The message should be shown <StatusCode>,<IsSuccess>,"<Message>"
	Examples:	
	| Level1 | Level2   | Level3              | Level4            | Level5     | Level6 | Level7 | Value                                                                                                                                 | StatusCode | IsSuccess | Message                                                                                   |
	| Risk   | Proposer | Id                  |                   |            |        |        | null                                                                                                                                  | 400        | FALSE     | Proposer must be 1.                  |
	| Risk   | Proposer | Id                  |                   |            |        |        | 2                                                                                                                                     | 400        | FALSE     | Proposer must be 1.                                                                       |
	| Risk   | Proposer | Id                  |                   |            |        |        | missing                                                                                                                               | 400        | FALSE     | Proposer must be 1.                                                                       |
	| Risk   | Proposer | Title               |                   |            |        |        | missing                                                                                                                               | 400        | FALSE     | Title is required.                                                                        |
	| Risk   | Proposer | Title               |                   |            |        |        | null                                                                                                                                  | 400        | FALSE     | Title is required.                                                                        |
	| Risk   | Proposer | Title               |                   |            |        |        | ""                                                                                                                                    | 400        | FALSE     | Title is required.                                                                        |
	| Risk   | Proposer | Forenames           |                   |            |        |        | missing                                                                                                                               | 400        | FALSE     | Forenames is required.                                                                    |
	| Risk   | Proposer | Forenames           |                   |            |        |        | null                                                                                                                                  | 400        | FALSE     | Forenames is required.                                                                    |
	| Risk   | Proposer | Forenames           |                   |            |        |        | ""                                                                                                                                    | 400        | FALSE     | Forenames is required.                                                                    |
	| Risk   | Proposer | Forenames           |                   |            |        |        | Selena Gomz qazxswedcrfvbgtyhnm                                                                                                       | 400        | FALSE     | Forenames cannot be over 30 characters.                                                   |
	| Risk   | Proposer | Surname             |                   |            |        |        | missing                                                                                                                               | 400        | FALSE     | Surname is required.                                                                      |
	| Risk   | Proposer | Surname             |                   |            |        |        | null                                                                                                                                  | 400        | FALSE     | Surname is required.                                                                      |
	| Risk   | Proposer | Surname             |                   |            |        |        | ""                                                                                                                                    | 400        | FALSE     | Surname is required.                                                                      |
	| Risk   | Proposer | Surname             |                   |            |        |        | Harris-Smith qqqer eg                                                                                                                 | 400        | FALSE     | Surname can not be over 20 characters.                                                    |
	| Risk   | Proposer | DateOfBirth         |                   |            |        |        | missing                                                                                                                               | 400        | FALSE     | DateOfBirth is required.                                                                  |
	| Risk   | Proposer | DateOfBirth         |                   |            |        |        | null                                                                                                                                  | 400        | FALSE     | DateOfBirth is required.                                                                  |
	| Risk   | Proposer | DateOfBirth         |                   |            |        |        | ""                                                                                                                                    | 400        | FALSE     | DateOfBirth is required.                                                                  |
	| Risk   | Proposer | UKResidentSinceDate |                   |            |        |        | missing                                                                                                                               | 400        | FALSE     | UKResidentSinceDate is required.                                                          |
	| Risk   | Proposer | UKResidentSinceDate |                   |            |        |        | null                                                                                                                                  | 400        | FALSE     | UKResidentSinceDate is required.                                                          |
	| Risk   | Proposer | UKResidentSinceDate |                   |            |        |        | ""                                                                                                                                    | 400        | FALSE     | UKResidentSinceDate is required.                                                          |
	| Risk   | Proposer | UKResidentSinceDate |                   |            |        |        | 1969-12-16T00:00:00                                                                                                                   | 400        | FALSE     | something went wrong                               |
	| Risk   | Proposer | MaritalStatus       |                   |            |        |        | missing                                                                                                                               | 400        | FALSE     | MaritalStatus is required.                                                                |
	| Risk   | Proposer | MaritalStatus       |                   |            |        |        | null                                                                                                                                  | 400        | FALSE     | MaritalStatus is required.                                                                |
	| Risk   | Proposer | MaritalStatus       |                   |            |        |        | ""                                                                                                                                    | 400        | FALSE     | MaritalStatus is required.                                                                |
	| Risk   | Proposer | Employment          |                   |            |        |        | missing                                                                                                                               | 400        | FALSE     | At least one Employment is required.                                                      |
	| Risk   | Proposer | Employment          |                   |            |        |        | null                                                                                                                                  | 400        | FALSE     | At least one Employment is required.                                                      |
	| Risk   | Proposer | Employment          |                   |            |        |        | File: ProposerEmployment602CNSBike.json                                                                                               | 400        | FALSE     | At least one Employment is required.                                                      |
	| Risk   | Proposer | Employment          | Type              |            |        |        | missing                                                                                                                               | 400        | FALSE     | Employment - Typeis required.                                                             |
	| Risk   | Proposer | Employment          | Type              |            |        |        | null                                                                                                                                  | 400        | FALSE     | Employment - Typeis required.                                                             |
	| Risk   | Proposer | Employment          | Type              |            |        |        | ""                                                                                                                                    | 400        | FALSE     | Employment - Typeis required.                                                             |
	| Risk   | Proposer | Employment          | Type              |            |        |        | Test                                                                                                                                  | 400        | FALSE     | Employment - Type must be fulltime/parttime/selfemployed.                                 |
	| Risk   | Proposer | Employment          | EmploymentCode    |            |        |        | missing                                                                                                                               | 400        | FALSE     | Employment - EmploymentCode is required.                                                  |
	| Risk   | Proposer | Employment          | EmploymentCode    |            |        |        | null                                                                                                                                  | 400        | FALSE     | Employment - EmploymentCode is required.                                                  |
	| Risk   | Proposer | Employment          | EmploymentCode    |            |        |        | ""                                                                                                                                    | 400        | FALSE     | Employment - EmploymentCode is required.                                                  |
	| Risk   | Proposer | Employment          | OccupationCode    |            |        |        | missing                                                                                                                               | 400        | FALSE     | Employment - OCcupationCode is required with EmploymentCode # R, U, H.                    |
	| Risk   | Proposer | Employment          | OccupationCode    |            |        |        | null                                                                                                                                  | 400        | FALSE     | Employment - OCcupationCode is required with EmploymentCode # R, U, H.                    |
	| Risk   | Proposer | Employment          | OccupationCode    |            |        |        | ""                                                                                                                                    | 400        | FALSE     | Employment - OCcupationCode is required with EmploymentCode # R, U, H.                    |
	| Risk   | Proposer | DrivingLicence      | Type              |            |        |        | missing                                                                                                                               | 400        | FALSE     | Driving Licence - Type is required.                                                       |
	| Risk   | Proposer | DrivingLicence      | Type              |            |        |        | null                                                                                                                                  | 400        | FALSE     | Driving Licence - Type is required.                                                       |
	| Risk   | Proposer | DrivingLicence      | Type              |            |        |        | ""                                                                                                                                    | 400        | FALSE     | Driving Licence - Type is required.                                                       |
	| Risk   | Proposer | DrivingLicence      | DateObtained      |            |        |        | missing                                                                                                                               | 400        | FALSE     | Licence date is required.                                                                 |
	| Risk   | Proposer | DrivingLicence      | DateObtained      |            |        |        | null                                                                                                                                  | 400        | FALSE     | Licence date is required.                                                                 |
	| Risk   | Proposer | DrivingLicence      | DateObtained      |            |        |        | ""                                                                                                                                    | 400        | FALSE     | Licence date is required.                                                                 |
	| Risk   | Proposer | DrivingLicence      | DateObtained      |            |        |        | 2021-12-16T00:00:00                                                                                                                   | 200        | true      | Get quote successfully                                                                    |
	| Risk   | Proposer | PhoneNumbers        |                   |            |        |        | missing                                                                                                                               | 400        | FALSE     | At least one Phone Number element is required.                                            |
	| Risk   | Proposer | PhoneNumbers        |                   |            |        |        | null                                                                                                                                  | 400        | FALSE     | At least one Phone Number element is required.                                            |
	| Risk   | Proposer | PhoneNumbers        |                   |            |        |        | File: ProposerPhoneNumbers637CNSBike.json                                                                                             | 400        | FALSE     | At least one Phone Number element is required.                                            |
	| Risk   | Proposer | PhoneNumbers        | Type              |            |        |        | missing                                                                                                                               | 400        | FALSE     | PhoneNumber - Type is required.                                                           |
	| Risk   | Proposer | PhoneNumbers        | Type              |            |        |        | null                                                                                                                                  | 400        | FALSE     | PhoneNumber - Type is required.                                                           |
	| Risk   | Proposer | PhoneNumbers        | Type              |            |        |        | ""                                                                                                                                    | 400        | FALSE     | PhoneNumber - Type is required.                                                           |
	| Risk   | Proposer | PhoneNumbers        | Number            |            |        |        | missing                                                                                                                               | 400        | FALSE     | PhoneNumber - Number is required.                                                         |
	| Risk   | Proposer | PhoneNumbers        | Number            |            |        |        | null                                                                                                                                  | 400        | FALSE     | PhoneNumber - Number is required.                                                         |
	| Risk   | Proposer | PhoneNumbers        | Number            |            |        |        | ""                                                                                                                                    | 400        | FALSE     | PhoneNumber - Number is required.                                                         |
	| Risk   | Proposer | PhoneNumbers        | Number            |            |        |        | 12345678                                                                                                                              | 400        | FALSE     | PhoneNumber - Number must be from 9 ~ 14 characters.                                      |
	| Risk   | Proposer | PhoneNumbers        | Number            |            |        |        | 123456789123456                                                                                                                       | 400        | FALSE     | PhoneNumber - Number must be from 9 ~ 14 characters.                                      |
	| Risk   | Proposer | Address             | AddressLine1      |            |        |        | missing                                                                                                                               | 400        | FALSE     | AddressLine1 is required.                                                                 |
	| Risk   | Proposer | Address             | AddressLine1      |            |        |        | null                                                                                                                                  | 400        | FALSE     | AddressLine1 is required.                                                                 |
	| Risk   | Proposer | Address             | AddressLine1      |            |        |        | ""                                                                                                                                    | 400        | FALSE     | AddressLine1 is required.                                                                 |
	| Risk   | Proposer | Address             | AddressLine1      |            |        |        | UK road 12UK road 12UK road 12123                                                                                                     | 400        | FALSE     | AddressLine1 cannot be over 32 characters.                                                |
	| Risk   | Proposer | Address             | AddressLine2      |            |        |        | missing                                                                                                                               | 400        | FALSE     | AddressLine2 is required.                                                                 |
	| Risk   | Proposer | Address             | AddressLine2      |            |        |        | null                                                                                                                                  | 400        | FALSE     | AddressLine2 is required.                                                                 |
	| Risk   | Proposer | Address             | AddressLine2      |            |        |        | ""                                                                                                                                    | 400        | FALSE     | AddressLine2 is required.                                                                 |
	| Risk   | Proposer | Address             | AddressLine2      |            |        |        | UK road 12UK road 12UK road 12123                                                                                                     | 400        | FALSE     | AddressLine2 cannot be over 32 characters.                                                |
	| Risk   | Proposer | Address             | AddressLine3      |            |        |        | UK road 12UK road 12UK road 12123                                                                                                     | 400        | FALSE     | AddressLine3 cannot be over 32 characters.                                                |
	| Risk   | Proposer | Address             | AddressLine4      |            |        |        | UK road 12UK road 12UK road 12123                                                                                                     | 400        | FALSE     | AddressLine4 cannot be over 32 characters.                                                |
	| Risk   | Proposer | Address             | PostCode          |            |        |        | missing                                                                                                                               | 400        | FALSE     | PostCode is required.                                                                     |
	| Risk   | Proposer | Address             | PostCode          |            |        |        | null                                                                                                                                  | 400        | FALSE     | PostCode is required.                                                                     |
	| Risk   | Proposer | Address             | PostCode          |            |        |        | ""                                                                                                                                    | 400        | FALSE     | PostCode is required.                                                                     |
	| Risk   | Proposer | Address             | PostCode          |            |        |        | EC2N 94AY                                                                                                                             | 400        | FALSE     | PostCode is invalid.                                                                      |
	| Risk   | Proposer | EmailAddress        |                   |            |        |        | missing                                                                                                                               | 400        | FALSE     | EmailAddress is required.                                                                 |
	| Risk   | Proposer | EmailAddress        |                   |            |        |        | null                                                                                                                                  | 400        | FALSE     | EmailAddress is required.                                                                 |
	| Risk   | Proposer | EmailAddress        |                   |            |        |        | ""                                                                                                                                    | 400        | FALSE     | EmailAddress is required.                                                                 |
	| Risk   | Proposer | EmailAddress        |                   |            |        |        | thuongnguyenthiminh@nashtech                                                                                                          | 400        | FALSE     | EmailAddress is invalid.                                                                  |
	| Risk   | Proposer | NCB                 | Years             |            |        |        | missing                                                                                                                               | 400        | FALSE     | Ncb - Years is required.                                                                  |
	| Risk   | Proposer | NCB                 | Years             |            |        |        | null                                                                                                                                  | 400        | FALSE     | Ncb - Years is required.                                                                  |
	| Risk   | Proposer | NCB                 | Years             |            |        |        | ""                                                                                                                                    | 400        | FALSE     | Ncb - Years is required.                                                                  |
	| Risk   | Proposer | Preferences         | Type              |            |        |        | missing                                                                                                                               | 400        | FALSE     | Preferences - Type is required.                                                           |
	| Risk   | Proposer | Preferences         | Type              |            |        |        | null                                                                                                                                  | 400        | FALSE     | Preferences - Type is required.                                                           |
	| Risk   | Proposer | Preferences         | Type              |            |        |        | ""                                                                                                                                    | 400        | FALSE     | Preferences - Type is required.                                                           |
	| Risk   | Proposer | Preferences         | Type              |            |        |        | Test                                                                                                                                  | 400        | FALSE     | Preferences - Type is invalid.                                                            |
	| Risk   | Proposer | Preferences         | SubType           |            |        |        | missing                                                                                                                               | 400        | FALSE     | Preferences - SubType is required.                                                        |
	| Risk   | Proposer | Preferences         | SubType           |            |        |        | null                                                                                                                                  | 400        | FALSE     | Preferences - SubType is required.                                                        |
	| Risk   | Proposer | Preferences         | SubType           |            |        |        | ""                                                                                                                                    | 400        | FALSE     | Preferences - SubType is required.                                                        |
	| Risk   | Proposer | Preferences         | SubType           |            |        |        | Test                                                                                                                                  | 400        | FALSE     | Preferences - SubType is invalid.                                                         |
	| Risk   | Product  | Vehicle             | AdditionalDrivers |            |        |        | File: VehicleAdditionalDrives684CNSBike.json                                                                                          | 400        | FALSE     | Additional rider's ID must be 2, 3, 4 or 5.Number of additional drivers cannot be over 4. |
	| Risk   | Product  | Vehicle             | AdditionalDrivers | Id         |        |        | ""                                                                                                                                    | 400        | FALSE     | Additional rider's ID is required.                                                        |
	| Risk   | Product  | Vehicle             | AdditionalDrivers | Id         |        |        | null                                                                                                                                  | 400        | FALSE     | Additional rider's ID is required.                                                        |
	| Risk   | Product  | Vehicle             | AdditionalDrivers | Id         |        |        | missing                                                                                                                               | 400        | FALSE     | Additional rider's ID is required.                                                        |
	| Risk   | Product  | Vehicle             | AdditionalDrivers | Id         |        |        | 1                                                                                                                                     | 400        | FALSE     | Additional rider's ID must be 2, 3, 4 or 5.                                               |
	| Risk   | Product  | Vehicle             | AdditionalDrivers | Id         |        |        | 6                                                                                                                                     | 400        | FALSE     | Additional rider's ID must be 2, 3, 4 or 5.                                               |
	| Risk   | Product  | Vehicle             | AdditionalDrivers |            |        |        | File: VehicleAdditionalDrives690CNSBike.json                                                                                          | 400        | FALSE     | Additional rider's ID must be unique.                                                     |
	| Risk   | Product  | Vehicle             | AdditionalDrivers | Salutation |        |        | Mrs Selena abcdfgtrgfdabcdfgtrgfdabcdfgtrgfdabcdfgtrgfdabcdfgtrgfdabcdfgtrgfdabcdfgtrgfdabcdfgtrgfdabcdfgtrgfdabcdfgtrgfdabcdfgtrgfdr | 200        | FALSE     |                                                                                           |
	| Risk   | Product  | Vehicle             | AdditionalDrivers | Title      |        |        | missing                                                                                                                               | 400        | FALSE     | Title is required.                                                                        |
	| Risk   | Product  | Vehicle             | AdditionalDrivers | Title      |        |        | null                                                                                                                                  | 400        | FALSE     | Title is required.                                                                        |