// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AtlantaApi.Feature.ANVanClassic.WebHookService.V3
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "AutonetVan")]
    public partial class SendARequestWebhookNormalCaseV3Feature : object, Xunit.IClassFixture<SendARequestWebhookNormalCaseV3Feature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = new string[] {
                "AutonetVan"};
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "PaymentOutcomeNormalCase.feature"
#line hidden
        
        public SendARequestWebhookNormalCaseV3Feature(SendARequestWebhookNormalCaseV3Feature.FixtureData fixtureData, AtlantaApi_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Feature/ANVanClassic/WebHookService/V3", "Send a request Webhook normal case V3", null, ProgrammingLanguage.CSharp, new string[] {
                        "AutonetVan"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Send a Webhook request normal case")]
        [Xunit.TraitAttribute("FeatureTitle", "Send a request Webhook normal case V3")]
        [Xunit.TraitAttribute("Description", "Send a Webhook request normal case")]
        [Xunit.TraitAttribute("Category", "WebhookServices")]
        [Xunit.InlineDataAttribute("200", "pc/confirmation?", new string[0])]
        public virtual void SendAWebhookRequestNormalCase(string statusCode, string messages, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "WebhookServices"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("StatusCode", statusCode);
            argumentsOfScenario.Add("Messages", messages);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Send a Webhook request normal case", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 10
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table115 = new TechTalk.SpecFlow.Table(new string[] {
                            "Property",
                            "Value"});
                table115.AddRow(new string[] {
                            "Uri",
                            "/api/V2/payment/outcome/A|AN|Autonet%20Van|GV|VNET"});
                table115.AddRow(new string[] {
                            "WebHookBody",
                            "WebHookBodyAutonetVan.json"});
                table115.AddRow(new string[] {
                            "QuoteRequestBody",
                            "ValidQuoteAutonetVanSuccess.json"});
                table115.AddRow(new string[] {
                            "PaymentRequestBody",
                            "RegisterPaymentRequestBodyAutonetVan.json"});
                table115.AddRow(new string[] {
                            "SaveMarketingRequestBody",
                            "SaveMarketingRequestBodyAutonetVan.json"});
                table115.AddRow(new string[] {
                            "SaveDebitRequestBody",
                            "SaveDebitRequestBodyAutonetVan.json"});
                table115.AddRow(new string[] {
                            "SavePaymentInfoRequestBody",
                            "SavePaymentInfoRequestBodyAutonetVan.json"});
                table115.AddRow(new string[] {
                            "ApiVersion",
                            "V3"});
                table115.AddRow(new string[] {
                            "ContextName",
                            "AutonetVan"});
#line 11
 testRunner.Given("I have wrapUp table", ((string)(null)), table115, "Given ");
#line hidden
#line 23
 testRunner.When("User send a Register PayInFull Payment service", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 24
 testRunner.And("User send a WebHook service", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 25
 testRunner.Then(string.Format("Payment response returns {0} and {1}", statusCode, messages), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                SendARequestWebhookNormalCaseV3Feature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                SendARequestWebhookNormalCaseV3Feature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
