#Cover 471 cases
@ScenicMH
Feature: QuoteSingleFieldDataValidationCasesPart3

@QuoteServices
Scenario Outline: ValiDate quote API on each field
	Given The customer has 
	| Name         | Value1                             |
	| Url          | QuoteApi                           |
	| ApiVersion   | V2                                 |
	| Context      | ScenicMotorHome                    |
	| JsonBodyFile | ValidQuoteForScenicMHGetQuote.json |
	When The customer call quote API
		| Level1   | Level2   | Level3   | Level4   | Level5   | Level6   | Level7   | Value   |
		| <Level1> | <Level2> | <Level3> | <Level4> | <Level5> | <Level6> | <Level7> | <Value> |
	Then The message should be shown <StatusCode>,<IsSuccess>,"<Message>"
	Examples:	
	| Level1 | Level2       | Level3                  | Level4            | Level5                  | Level6 | Level7 | Value                              | StatusCode | IsSuccess | Message                                                                                           |
	| Risk   | Product      | Vehicle                 | VehicleDetail     | Seats                   |        |        | ""                                 | 400        | FALSE     | Seats is required.                                                                                |
	| Risk   | Product      | Vehicle                 | VehicleDetail     | Seats                   |        |        | null                               | 400        | FALSE     | Seats is required.                                                                                |
	| Risk   | Product      | Vehicle                 | VehicleDetail     | Seats                   |        |        | missing                            | 400        | FALSE     | Seats is required.                                                                                |
	| Risk   | Product      | Vehicle                 | VehicleDetail     | HandednessDrivingType   |        |        | ""                                 | 400        | FALSE     | HandednessDrivingType is required.                                                                |
	| Risk   | Product      | Vehicle                 | VehicleDetail     | HandednessDrivingType   |        |        | null                               | 400        | FALSE     | HandednessDrivingType is required.                                                                |
	| Risk   | Product      | Vehicle                 | VehicleDetail     | HandednessDrivingType   |        |        | missing                            | 400        | FALSE     | HandednessDrivingType is required.                                                                |
	| Risk   | Product      | Vehicle                 | VehicleDetail     | HandednessDrivingType   |        |        | abc                                | 400        | FALSE     | HandednessDrivingType is invalid                                                                  |
	| Risk   | Product      | Vehicle                 | VehicleDetail     | DatePurchased           |        |        | ""                                 | 400        | FALSE     | DatePurchased is required.                                                                        |
	| Risk   | Product      | Vehicle                 | VehicleDetail     | DatePurchased           |        |        | null                               | 400        | FALSE     | DatePurchased is required.                                                                        |
	| Risk   | Product      | Vehicle                 | VehicleDetail     | DatePurchased           |        |        | missing                            | 400        | FALSE     | DatePurchased is required.                                                                        |
	| Risk   | Product      | Vehicle                 | VehicleDetail     | Owner                   |        |        | null                               | 400        | FALSE     | Owner is required.                                                                                |
	| Risk   | Product      | Vehicle                 | VehicleDetail     | Owner                   |        |        | missing                            | 400        | FALSE     | Owner is required.                                                                                |
	| Risk   | Product      | Vehicle                 | VehicleDetail     | Owner                   |        |        | ""                                 | 400        | FALSE     | Owner is required.                                                                                |
	| Risk   | Product      | Vehicle                 | VehicleDetail     | RegisteredKeeper        |        |        | ""                                 | 400        | FALSE     | RegisteredKeeper is required.                                                                     |
	| Risk   | Product      | Vehicle                 | VehicleDetail     | RegisteredKeeper        |        |        | null                               | 400        | FALSE     | RegisteredKeeper is required.                                                                     |
	| Risk   | Product      | Vehicle                 | VehicleDetail     | RegisteredKeeper        |        |        | missing                            | 400        | FALSE     | RegisteredKeeper is required.                                                                     |
	| Risk   | Product      | Vehicle                 | VehicleDetail     | LocationParkedOvernight |        |        | ""                                 | 400        | FALSE     | LocationParkedOvernight is required.                                                              |
	| Risk   | Product      | Vehicle                 | VehicleDetail     | LocationParkedOvernight |        |        | null                               | 400        | FALSE     | LocationParkedOvernight is required.                                                              |
	| Risk   | Product      | Vehicle                 | VehicleDetail     | LocationParkedOvernight |        |        | missing                            | 400        | FALSE     | LocationParkedOvernight is required.                                                              |
	| Risk   | Product      | Vehicle                 | VehicleDetail     | PostCodeParkedOvernight |        |        | ""                                 | 400        | FALSE     | PostCodeParkedOvernight is required.                                                              |
	| Risk   | Product      | Vehicle                 | VehicleDetail     | PostCodeParkedOvernight |        |        | null                               | 400        | FALSE     | PostCodeParkedOvernight is required.                                                              |
	| Risk   | Product      | Vehicle                 | VehicleDetail     | PostCodeParkedOvernight |        |        | missing                            | 400        | FALSE     | PostCodeParkedOvernight is required.                                                              |
	| Risk   | Product      | Vehicle                 | VehicleDetail     | PostCodeParkedOvernight |        |        | abcdfdd                            | 400        | FALSE     | PostCodeParkedOvernight is incorrect.                                                             |
	| Risk   | Product      | Vehicle                 | VehicleDetail     | ClassOfUse              |        |        | ""                                 | 400        | FALSE     | ClassOfUse is required.                                                                           |
	| Risk   | Product      | Vehicle                 | VehicleDetail     | ClassOfUse              |        |        | null                               | 400        | FALSE     | ClassOfUse is required.                                                                           |
	| Risk   | Product      | Vehicle                 | VehicleDetail     | ClassOfUse              |        |        | missing                            | 400        | FALSE     | ClassOfUse is required.                                                                           |
	| Risk   | Product      | Vehicle                 | VehicleDetail     | Mileage                 |        |        | File: VehicleDetailMileage871.json | 400        | FALSE     | At least one mileage element must be added.                                                       |
	| Risk   | Product      | Vehicle                 | VehicleDetail     | Mileage                 |        |        | missing                            | 400        | FALSE     | At least one mileage element must be added.                                                       |
	| Risk   | Product      | Vehicle                 | VehicleDetail     | Mileage                 |        |        | null                               | 400        | FALSE     | At least one mileage element must be added.                                                       |
	| Risk   | Product      | Vehicle                 | VehicleDetail     | Mileage                 | Type   |        | ""                                 | 400        | FALSE     | Mileage - Type is required.                                                                       |
	| Risk   | Product      | Vehicle                 | VehicleDetail     | Mileage                 | Type   |        | null                               | 400        | FALSE     | Mileage - Type is required.                                                                       |
	| Risk   | Product      | Vehicle                 | VehicleDetail     | Mileage                 | Type   |        | missing                            | 400        | FALSE     | Mileage - Type is required.                                                                       |
	| Risk   | Product      | Vehicle                 | VehicleDetail     | Mileage                 | Type   |        | Test                               | 400        | FALSE     | Mileage - Type is invalid.                                                                        |
	| Risk   | Product      | Vehicle                 | VehicleDetail     | Mileage                 | Value  |        | ""                                 | 400        | FALSE     | Mileage - Value is required.                                                                      |
	| Risk   | Product      | Vehicle                 | VehicleDetail     | Mileage                 | Value  |        | null                               | 400        | FALSE     | Mileage - Value is required.                                                                      |
	| Risk   | Product      | Vehicle                 | VehicleDetail     | Mileage                 | Value  |        | missing                            | 400        | FALSE     | Mileage - Value is required.                                                                      |
	| Risk   | Product      | Vehicle                 | VehicleDetail     | Mileage                 | Value  |        | 99                                 | 400        | FALSE     | Mileage - Value must be a number from 100 ~ 999999.                                               |
	| Risk   | Product      | Vehicle                 | VehicleDetail     | Mileage                 | Value  |        | 1000000                            | 400        | FALSE     | Mileage - Value must be a number from 100 ~ 999999.                                               |
	| Risk   | Product      | Vehicle                 | VehicleDetail     | Mileage                 | Value  |        | abc                                | 400        | FALSE     | Mileage - Value must be a number from 100 ~ 999999.                                               |
	| Risk   | Product      | Vehicle                 | VehicleDetail     | CurrentValue            |        |        | ""                                 | 400        | FALSE     | CurrentValue is required.                                                                         |
	| Risk   | Product      | Vehicle                 | VehicleDetail     | CurrentValue            |        |        | null                               | 400        | FALSE     | CurrentValue is required.                                                                         |
	| Risk   | Product      | Vehicle                 | VehicleDetail     | CurrentValue            |        |        | missing                            | 400        | FALSE     | CurrentValue is required.                                                                         |
	| Risk   | Product      | Vehicle                 | VehicleDetail     | CurrentValue            |        |        | -1                                 | 400        | FALSE     | CurrentValue must be a positive number from 0 ~ 999999.                                           |
	| Risk   | Product      | Vehicle                 | VehicleDetail     | PurchasePrice           |        |        | ""                                 | 400        | FALSE     | PurchasePrice is required.                                                                        |
	| Risk   | Product      | Vehicle                 | VehicleDetail     | PurchasePrice           |        |        | null                               | 400        | FALSE     | PurchasePrice is required.                                                                        |
	| Risk   | Product      | Vehicle                 | VehicleDetail     | PurchasePrice           |        |        | missing                            | 400        | FALSE     | PurchasePrice is required.                                                                        |
	| Risk   | Product      | Vehicle                 | VehicleDetail     | CoverType               |        |        | ""                                 | 400        | FALSE     | CoverType is required.                                                                            |
	| Risk   | Product      | Vehicle                 | VehicleDetail     | CoverType               |        |        | null                               | 400        | FALSE     | CoverType is required.                                                                            |
	| Risk   | Product      | Vehicle                 | VehicleDetail     | CoverType               |        |        | missing                            | 400        | FALSE     | CoverType is required.                                                                            |
	| Risk   | Product      | Vehicle                 | VehicleDetail     | MainDriverId            |        |        | ""                                 | 400        | FALSE     | Maindriverid is required                                                                          |
	| Risk   | Product      | Vehicle                 | VehicleDetail     | MainDriverId            |        |        | null                               | 400        | FALSE     | Maindriverid is required                                                                          |
	| Risk   | Product      | Vehicle                 | VehicleDetail     | MainDriverId            |        |        | missing                            | 400        | FALSE     | MainDriverId is required.                                                                         |
	| Risk   | Product      | Vehicle                 | VehicleDetail     | MainDriverId            |        |        | 10                                 | 400        | FALSE     | MainDriverId does not match any driver in request.                                                |
	| Risk   | WebReference |                         |                   |                         |        |        | 435-444-xxx-543                    | 400        | FALSE     | WebReference is invalid.                                                                          |
	| Risk   | Product      | HowDoYouPayForInsurance |                   |                         |        |        | null                               | 400        | FALSE     | HowDoYouPayForInsurance is required.                                                              |
	| Risk   | Product      | HowDoYouPayForInsurance |                   |                         |        |        | ""                                 | 400        | FALSE     | HowDoYouPayForInsurance is required.                                                              |
	| Risk   | Product      | HowDoYouPayForInsurance |                   |                         |        |        | missing                            | 400        | FALSE     | HowDoYouPayForInsurance is required.                                                              |
	| Risk   | Product      | PolicyStartDate         |                   |                         |        |        | 2020-09-16T00:00:00                | 400        | FALSE     | PolicyStartDate cannot be in the past.                                                            |
	| Risk   | Product      | PolicyStartDate         |                   |                         |        |        | null                               | 400        | FALSE     | PolicyStartDate is required                                                                       |
	| Risk   | Product      | PolicyStartDate         |                   |                         |        |        | ""                                 | 400        | FALSE     | PolicyStartDate is required                                                                       |
	| Risk   | Product      | PolicyStartDate         |                   |                         |        |        | missing                            | 400        | FALSE     | PolicyStartDate is required.                                                                      |
	| Risk   | Product      | VoluntaryExcess         |                   |                         |        |        | -1                                 | 400        | FALSE     | VoluntaryExcess must be integer greater than or equal 0.                                          |
	| Risk   | Product      | VoluntaryExcess         |                   |                         |        |        | 3.14                               | 400        | FALSE     | VoluntaryExcess must be integer greater than or equal 0.                                          |
	| Risk   | Product      | VoluntaryExcess         |                   |                         |        |        | abc                                | 400        | FALSE     | VoluntaryExcess must be integer greater than or equal 0.                                          |
	| Risk   | Product      | Claims                  |                   |                         |        |        | File: ProductClaims929.json        | 400        | FALSE     | Cannot quote for more than 5 claims.                                                              |
	| Risk   | Product      | Claims                  | PersonId          |                         |        |        | null                               | 400        | FALSE     | Error converting value {null} to type 'System.Int32'. Path 'Risk.Product.Claims[0].PersonId'      |
	| Risk   | Product      | Claims                  | PersonId          |                         |        |        | ""                                 | 400        | FALSE     | Error converting value {null} to type 'System.Int32'. Path 'Risk.Product.Claims[0].PersonId'      |
	| Risk   | Product      | Claims                  | PersonId          |                         |        |        | missing                            | 400        | FALSE     | Claim - PersonId is required.                                                                     |
	| Risk   | Product      | Claims                  | PersonId          |                         |        |        | 15                                 | 400        | FALSE     | Claim - PersonId does not match any driver in request.                                            |
	| Risk   | Product      | Claims                  | Code              |                         |        |        | null                               | 400        | FALSE     | Claim - Code is required.                                                                         |
	| Risk   | Product      | Claims                  | Code              |                         |        |        | ""                                 | 400        | FALSE     | Claim - Code is required.                                                                         |
	| Risk   | Product      | Claims                  | Code              |                         |        |        | missing                            | 400        | FALSE     | Claim - Code is required.                                                                         |
	| Risk   | Product      | Claims                  | Date              |                         |        |        | 2022-01-01                         | 400        | FALSE     | Claim - Date cannot be in future.                                                                 |
	| Risk   | Product      | Claims                  | NcbAffected       |                         |        |        | null                               | 400        | FALSE     | Claim - NcbAffected is required                                                                   |
	| Risk   | Product      | Claims                  | NcbAffected       |                         |        |        | ""                                 | 400        | FALSE     | Claim - NcbAffected is required                                                                   |
	| Risk   | Product      | Claims                  | NcbAffected       |                         |        |        | missing                            | 400        | FALSE     | Claim - NcbAffected is required                                                                   |
	| Risk   | Product      | Claims                  | Costs             |                         |        |        | -1                                 | 400        | FALSE     | Claim - Costs must be integer greater than or equal 0.                                            |
	| Risk   | Product      | Claims                  | Costs             |                         |        |        | missing                            | 400        | FALSE     | Claim - Costs must be integer greater than or equal 0.                                            |
	| Risk   | Product      | Claims                  | Costs             |                         |        |        | abc                                | 400        | FALSE     | Claim - Costs must be integer greater than or equal 0.                                            |
	| Risk   | Product      | Claims                  | ThirdPartyCost    |                         |        |        | -1                                 | 400        | FALSE     | Claim - ThirdPartyCost must be integer greater than or equal 0.                                   |
	| Risk   | Product      | Claims                  | ThirdPartyCost    |                         |        |        | 3.14                               | 400        | FALSE     | Claim - ThirdPartyCost must be integer greater than or equal 0.                                   |
	| Risk   | Product      | Claims                  | ThirdPartyCost    |                         |        |        | abc                                | 400        | FALSE     | Claim - ThirdPartyCost must be integer greater than or equal 0.                                   |
	| Risk   | Product      | Convictions             |                   |                         |        |        | File: ProductConvictions954.json   | 400        | FALSE     | Cannot quote for more than 5 Convictions.                                                         |
	| Risk   | Product      | Convictions             | PersonId          |                         |        |        | null                               | 400        | FALSE     | Error converting value {null} to type 'System.Int32'. Path 'Risk.Product.Convictions[0].PersonId' |
	| Risk   | Product      | Convictions             | PersonId          |                         |        |        | ""                                 | 400        | FALSE     | Error converting value {null} to type 'System.Int32'. Path 'Risk.Product.Convictions[0].PersonId' |
	| Risk   | Product      | Convictions             | PersonId          |                         |        |        | missing                            | 400        | FALSE     | Conviction - PersonId is required.                                                                |
	| Risk   | Product      | Convictions             | PersonId          |                         |        |        | 15                                 | 400        | FALSE     | Conviction - PersonId does not match any driver in request.                                       |
	| Risk   | Product      | Convictions             | Code              |                         |        |        | null                               | 400        | FALSE     | Conviction - Code is required.                                                                    |
	| Risk   | Product      | Convictions             | Code              |                         |        |        | ""                                 | 400        | FALSE     | Conviction - Code is required.                                                                    |
	| Risk   | Product      | Convictions             | Code              |                         |        |        | missing                            | 400        | FALSE     | Conviction - Code is required.                                                                    |
	| Risk   | Product      | Convictions             | Date              |                         |        |        | 2022-01-01                         | 400        | FALSE     | Conviction - Date cannot be in future.                                                            |
	| Risk   | Product      | Convictions             | BanLength         |                         |        |        | -1                                 | 400        | FALSE     | Conviction - BanLength must be integer greater than or equal 0.                                   |
	| Risk   | Product      | Convictions             | BanLength         |                         |        |        | 3.14                               | 400        | FALSE     | Conviction - BanLength must be integer greater than or equal 0.                                   |
	| Risk   | Product      | Convictions             | BanLength         |                         |        |        | abc                                | 400        | FALSE     | Conviction - BanLength must be integer greater than or equal 0.                                   |
	| Risk   | Product      | Convictions             | FineAmount        |                         |        |        | -1                                 | 400        | FALSE     | Conviction - FineAmount must be integer greater than or equal 0.                                  |
	| Risk   | Product      | Convictions             | FineAmount        |                         |        |        | 3.14                               | 400        | FALSE     | Conviction - FineAmount must be integer greater than or equal 0.                                  |
	| Risk   | Product      | Convictions             | FineAmount        |                         |        |        | abc                                | 400        | FALSE     | Conviction - FineAmount must be integer greater than or equal 0.                                  |
	| Risk   | Product      | Convictions             | PenaltyPoints     |                         |        |        | -1                                 | 400        | FALSE     | Conviction - PenaltyPoints must be integer greater than or equal 0.                               |
	| Risk   | Product      | Convictions             | PenaltyPoints     |                         |        |        | 3.14                               | 400        | FALSE     | Conviction - PenaltyPoints must be integer greater than or equal 0.                               |
	| Risk   | Product      | Convictions             | PenaltyPoints     |                         |        |        | abc                                | 400        | FALSE     | Conviction - PenaltyPoints must be integer greater than or equal 0.                               |
	| Risk   | Product      | Convictions             | DrinkReading      |                         |        |        | AB                                 | 400        | FALSE     | DrinkReading is invalid.                                                                          |
	| Risk   | Product      | Convictions             | DrinkReadingLevel |                         |        |        | 251                                | 400        | FALSE     | DrinkReadingLevel must be from 0 ~ 250.                                                           |